# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.AccessibilityTreeResponse do
  @moduledoc """
  AccessibilityTreeResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :root,
    :truncated
  ]

  @type t :: %__MODULE__{
          :root => ExDaytona.Model.ComputeruseAccessibilityNode.t() | nil,
          :truncated => boolean() | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:root, :struct, ExDaytona.Model.ComputeruseAccessibilityNode)
  end
end
