# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.ApiKeyResponse do
  @moduledoc """
  ApiKeyResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :createdAt,
    :expiresAt,
    :name,
    :permissions,
    :value
  ]

  @type t :: %__MODULE__{
          :createdAt => DateTime.t(),
          :expiresAt => DateTime.t() | nil,
          :name => String.t(),
          :permissions => [String.t()],
          :value => String.t()
        }

  def decode(value) do
    value
  end
end
