# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.AuditScenarios do
  @moduledoc """
  AuditScenarios model.
  """

  @derive JSON.Encoder
  defstruct [
    :targets
  ]

  @type t :: %__MODULE__{
          :targets => [ExDaytona.Model.AuditTargetScenario.t()]
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:targets, :list, ExDaytona.Model.AuditTargetScenario)
  end
end
