# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.AuditLog do
  @moduledoc """
  AuditLog model.
  """

  @derive JSON.Encoder
  defstruct [
    :action,
    :actorApiKeyPrefix,
    :actorApiKeySuffix,
    :actorEmail,
    :actorId,
    :createdAt,
    :errorMessage,
    :id,
    :ipAddress,
    :metadata,
    :organizationId,
    :source,
    :statusCode,
    :targetId,
    :targetType,
    :userAgent
  ]

  @type t :: %__MODULE__{
          :action => String.t(),
          :actorApiKeyPrefix => String.t() | nil,
          :actorApiKeySuffix => String.t() | nil,
          :actorEmail => String.t(),
          :actorId => String.t(),
          :createdAt => DateTime.t(),
          :errorMessage => String.t() | nil,
          :id => String.t(),
          :ipAddress => String.t() | nil,
          :metadata => %{optional(String.t()) => any()} | nil,
          :organizationId => String.t() | nil,
          :source => String.t() | nil,
          :statusCode => number() | nil,
          :targetId => String.t() | nil,
          :targetType => String.t() | nil,
          :userAgent => String.t() | nil
        }

  def decode(value) do
    value
  end
end
