# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.AvailableSandboxClass do
  @moduledoc """
  AvailableSandboxClass model.
  """

  @derive JSON.Encoder
  defstruct [
    :allowedGpuTypes,
    :gpuAvailable,
    :regionId,
    :sandboxClass
  ]

  @type t :: %__MODULE__{
          :allowedGpuTypes => [ExDaytona.Model.GpuType.t()] | nil,
          :gpuAvailable => boolean(),
          :regionId => String.t(),
          :sandboxClass => ExDaytona.Model.SandboxClass.t()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:allowedGpuTypes, :list, ExDaytona.Model.GpuType)
    |> Deserializer.deserialize(:sandboxClass, :struct, ExDaytona.Model.SandboxClass)
  end
end
