# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.AvailableSandboxClass do
  @moduledoc """
  AvailableSandboxClass model.
  """

  # Encode without nil fields: unset optional fields must be OMITTED from
  # request JSON, not sent as explicit nulls — real servers (Daytona
  # included) reject bodies full of nulls that a bare {} would satisfy.
  defimpl JSON.Encoder do
    def encode(struct, encoder) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_field, value} -> is_nil(value) end)
      |> Map.new()
      |> encoder.(encoder)
    end
  end

  defstruct [
    :allowedGpuTypes,
    :gpuAvailable,
    :regionId,
    :sandboxClass
  ]

  @type t :: %__MODULE__{
          :allowedGpuTypes => [ExDaytona.Model.GpuType.t()] | nil,
          :gpuAvailable => boolean(),
          :regionId => String.t(),
          :sandboxClass => ExDaytona.Model.SandboxClass.t()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:allowedGpuTypes, :list, ExDaytona.Model.GpuType)
    |> Deserializer.deserialize(:sandboxClass, :struct, ExDaytona.Model.SandboxClass)
  end
end
