# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.BuildInfo do
  @moduledoc """
  BuildInfo model.
  """

  @derive JSON.Encoder
  defstruct [
    :contextHashes,
    :createdAt,
    :dockerfileContent,
    :snapshotRef,
    :updatedAt
  ]

  @type t :: %__MODULE__{
          :contextHashes => [String.t()] | nil,
          :createdAt => DateTime.t(),
          :dockerfileContent => String.t() | nil,
          :snapshotRef => String.t(),
          :updatedAt => DateTime.t()
        }

  def decode(value) do
    value
  end
end
