# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.ChartElement do
  @moduledoc """
  ChartElement model.
  """

  @derive JSON.Encoder
  defstruct [
    :angle,
    :first_quartile,
    :group,
    :label,
    :max,
    :median,
    :min,
    :outliers,
    :png,
    :points,
    :radius,
    :third_quartile,
    :title,
    :type,
    :value,
    :x_label,
    :y_label
  ]

  @type t :: %__MODULE__{
          :angle => number() | nil,
          :first_quartile => number() | nil,
          :group => String.t() | nil,
          :label => String.t() | nil,
          :max => number() | nil,
          :median => number() | nil,
          :min => number() | nil,
          :outliers => [number()] | nil,
          :png => String.t() | nil,
          :points => [[number()]] | nil,
          :radius => number() | nil,
          :third_quartile => number() | nil,
          :title => String.t() | nil,
          :type => String.t() | nil,
          :value => String.t() | nil,
          :x_label => String.t() | nil,
          :y_label => String.t() | nil
        }

  def decode(value) do
    value
  end
end
