# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.CodeRunResponse do
  @moduledoc """
  CodeRunResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :artifacts,
    :exitCode,
    :result
  ]

  @type t :: %__MODULE__{
          :artifacts => ExDaytona.Model.CodeRunArtifacts.t() | nil,
          :exitCode => integer() | nil,
          :result => String.t() | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:artifacts, :struct, ExDaytona.Model.CodeRunArtifacts)
  end
end
