# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.CodeRunArtifacts do
  @moduledoc """
  CodeRunArtifacts model.
  """

  @derive JSON.Encoder
  defstruct [
    :charts
  ]

  @type t :: %__MODULE__{
          :charts => [ExDaytona.Model.Chart.t()] | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:charts, :list, ExDaytona.Model.Chart)
  end
end
