# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.CodeRunRequest do
  @moduledoc """
  CodeRunRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :argv,
    :code,
    :envs,
    :language,
    :timeout
  ]

  @type t :: %__MODULE__{
          :argv => [String.t()] | nil,
          :code => String.t(),
          :envs => %{optional(String.t()) => String.t()} | nil,
          :language => String.t(),
          :timeout => integer() | nil
        }

  def decode(value) do
    value
  end
end
