# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.CompletionItem do
  @moduledoc """
  CompletionItem model.
  """

  @derive JSON.Encoder
  defstruct [
    :detail,
    :documentation,
    :filterText,
    :insertText,
    :kind,
    :label,
    :sortText
  ]

  @type t :: %__MODULE__{
          :detail => String.t() | nil,
          :documentation => any() | nil,
          :filterText => String.t() | nil,
          :insertText => String.t() | nil,
          :kind => integer() | nil,
          :label => String.t(),
          :sortText => String.t() | nil
        }

  def decode(value) do
    value
  end
end
