# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.ComputeruseAccessibilityNode do
  @moduledoc """
  ComputeruseAccessibilityNode model.
  """

  @derive JSON.Encoder
  defstruct [
    :actions,
    :bounds,
    :children,
    :description,
    :id,
    :name,
    :role,
    :states
  ]

  @type t :: %__MODULE__{
          :actions => [String.t()] | nil,
          :bounds => ExDaytona.Model.AccessibilityBounds.t() | nil,
          :children => [ExDaytona.Model.ComputeruseAccessibilityNode.t()] | nil,
          :description => String.t() | nil,
          :id => String.t() | nil,
          :name => String.t() | nil,
          :role => String.t() | nil,
          :states => [String.t()] | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:bounds, :struct, ExDaytona.Model.AccessibilityBounds)
    |> Deserializer.deserialize(:children, :list, ExDaytona.Model.ComputeruseAccessibilityNode)
  end
end
