# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.CompletionList do
  @moduledoc """
  CompletionList model.
  """

  @derive JSON.Encoder
  defstruct [
    :isIncomplete,
    :items
  ]

  @type t :: %__MODULE__{
          :isIncomplete => boolean(),
          :items => [ExDaytona.Model.CompletionItem.t()]
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:items, :list, ExDaytona.Model.CompletionItem)
  end
end
