# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.CreateUser do
  @moduledoc """
  CreateUser model.
  """

  # Encode without nil fields: unset optional fields must be OMITTED from
  # request JSON, not sent as explicit nulls — real servers (Daytona
  # included) reject bodies full of nulls that a bare {} would satisfy.
  defimpl JSON.Encoder do
    def encode(struct, encoder) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_field, value} -> is_nil(value) end)
      |> Map.new()
      |> encoder.(encoder)
    end
  end

  defstruct [
    :email,
    :emailVerified,
    :emailVerifiedSource,
    :id,
    :name,
    :personalOrganizationDefaultRegionId,
    :personalOrganizationQuota,
    :role
  ]

  @type t :: %__MODULE__{
          :email => String.t() | nil,
          :emailVerified => boolean() | nil,
          :emailVerifiedSource => String.t() | nil,
          :id => String.t() | nil,
          :name => String.t(),
          :personalOrganizationDefaultRegionId => String.t() | nil,
          :personalOrganizationQuota => ExDaytona.Model.CreateOrganizationQuota.t() | nil,
          :role => String.t() | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:personalOrganizationQuota, :struct, ExDaytona.Model.CreateOrganizationQuota)
  end
end
