# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.CreateIdentityProvider do
  @moduledoc """
  CreateIdentityProvider model.
  """

  @derive JSON.Encoder
  defstruct [
    :allowAnyDomain,
    :defaultAssignedRoleIds,
    :emailDomains,
    :enabled,
    :name,
    :oidcConfig,
    :trustEmailVerified
  ]

  @type t :: %__MODULE__{
          :allowAnyDomain => boolean() | nil,
          :defaultAssignedRoleIds => [String.t()] | nil,
          :emailDomains => [String.t()],
          :enabled => boolean() | nil,
          :name => String.t(),
          :oidcConfig => ExDaytona.Model.OidcIdPConfig.t(),
          :trustEmailVerified => boolean() | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:oidcConfig, :struct, ExDaytona.Model.OidcIdPConfig)
  end
end
