# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.CreateSandbox do
  @moduledoc """
  CreateSandbox model.
  """

  @derive JSON.Encoder
  defstruct [
    :autoArchiveInterval,
    :autoDeleteInterval,
    :autoPauseInterval,
    :autoStopInterval,
    :buildInfo,
    :cpu,
    :disk,
    :domainAllowList,
    :env,
    :gpu,
    :gpuType,
    :labels,
    :linkedSandbox,
    :memory,
    :name,
    :networkAllowList,
    :networkBlockAll,
    :otelEndpointOverride,
    :outboundProxyUrl,
    :public,
    :secrets,
    :snapshot,
    :spot,
    :target,
    :ttlMinutes,
    :user,
    :volumes
  ]

  @type t :: %__MODULE__{
          :autoArchiveInterval => integer() | nil,
          :autoDeleteInterval => integer() | nil,
          :autoPauseInterval => integer() | nil,
          :autoStopInterval => integer() | nil,
          :buildInfo => ExDaytona.Model.CreateBuildInfo.t() | nil,
          :cpu => integer() | nil,
          :disk => integer() | nil,
          :domainAllowList => String.t() | nil,
          :env => %{optional(String.t()) => String.t()} | nil,
          :gpu => integer() | nil,
          :gpuType => [ExDaytona.Model.GpuType.t()] | nil,
          :labels => %{optional(String.t()) => String.t()} | nil,
          :linkedSandbox => String.t() | nil,
          :memory => integer() | nil,
          :name => String.t() | nil,
          :networkAllowList => String.t() | nil,
          :networkBlockAll => boolean() | nil,
          :otelEndpointOverride => String.t() | nil,
          :outboundProxyUrl => String.t() | nil,
          :public => boolean() | nil,
          :secrets => [%{optional(String.t()) => String.t()}] | nil,
          :snapshot => String.t() | nil,
          :spot => boolean() | nil,
          :target => String.t() | nil,
          :ttlMinutes => integer() | nil,
          :user => String.t() | nil,
          :volumes => [ExDaytona.Model.SandboxVolume.t()] | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:buildInfo, :struct, ExDaytona.Model.CreateBuildInfo)
    |> Deserializer.deserialize(:gpuType, :list, ExDaytona.Model.GpuType)
    |> Deserializer.deserialize(:volumes, :list, ExDaytona.Model.SandboxVolume)
  end
end
