# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.CreateSnapshot do
  @moduledoc """
  CreateSnapshot model.
  """

  @derive JSON.Encoder
  defstruct [
    :buildInfo,
    :cpu,
    :disk,
    :entrypoint,
    :gpu,
    :gpuType,
    :imageName,
    :memory,
    :name,
    :regionId,
    :sandboxClass
  ]

  @type t :: %__MODULE__{
          :buildInfo => ExDaytona.Model.CreateBuildInfo.t() | nil,
          :cpu => integer() | nil,
          :disk => integer() | nil,
          :entrypoint => [String.t()] | nil,
          :gpu => integer() | nil,
          :gpuType => [ExDaytona.Model.GpuType.t()] | nil,
          :imageName => String.t() | nil,
          :memory => integer() | nil,
          :name => String.t(),
          :regionId => String.t() | nil,
          :sandboxClass => ExDaytona.Model.SandboxClass.t() | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:buildInfo, :struct, ExDaytona.Model.CreateBuildInfo)
    |> Deserializer.deserialize(:gpuType, :list, ExDaytona.Model.GpuType)
    |> Deserializer.deserialize(:sandboxClass, :struct, ExDaytona.Model.SandboxClass)
  end
end
