# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.CreateOrganizationQuota do
  @moduledoc """
  CreateOrganizationQuota model.
  """

  @derive JSON.Encoder
  defstruct [
    :maxConcurrentSnapshotProcessing,
    :maxCpuPerSandbox,
    :maxDiskPerSandbox,
    :maxMemoryPerSandbox,
    :maxSnapshotSize,
    :snapshotQuota,
    :totalCpuQuota,
    :totalDiskQuota,
    :totalGpuQuota,
    :totalMemoryQuota,
    :volumeQuota
  ]

  @type t :: %__MODULE__{
          :maxConcurrentSnapshotProcessing => number() | nil,
          :maxCpuPerSandbox => number() | nil,
          :maxDiskPerSandbox => number() | nil,
          :maxMemoryPerSandbox => number() | nil,
          :maxSnapshotSize => number() | nil,
          :snapshotQuota => number() | nil,
          :totalCpuQuota => number() | nil,
          :totalDiskQuota => number() | nil,
          :totalGpuQuota => number() | nil,
          :totalMemoryQuota => number() | nil,
          :volumeQuota => number() | nil
        }

  def decode(value) do
    value
  end
end
