# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.CreateSandbox do
  @moduledoc """
  CreateSandbox model.
  """

  # Credential-safe inspection: fields whose names indicate credentials
  # (tokens, keys, secrets, passwords) render as "[REDACTED]" — see
  # ExDaytona.Redact. Regeneration cannot remove this protection
  # because it lives in the model template.
  defimpl Inspect do
    def inspect(struct, opts), do: ExDaytona.Redact.inspect_struct(struct, opts)
  end

  # Encode without nil fields: unset optional fields must be OMITTED from
  # request JSON, not sent as explicit nulls — real servers (Daytona
  # included) reject bodies full of nulls that a bare {} would satisfy.
  defimpl JSON.Encoder do
    def encode(struct, encoder) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_field, value} -> is_nil(value) end)
      |> Map.new()
      |> encoder.(encoder)
    end
  end

  defstruct [
    :autoArchiveInterval,
    :autoDeleteInterval,
    :autoPauseInterval,
    :autoStopInterval,
    :buildInfo,
    :cpu,
    :disk,
    :domainAllowList,
    :env,
    :gpu,
    :gpuType,
    :labels,
    :linkedSandbox,
    :memory,
    :name,
    :networkAllowList,
    :networkBlockAll,
    :otelEndpointOverride,
    :outboundProxyUrl,
    :public,
    :secrets,
    :snapshot,
    :spot,
    :target,
    :ttlMinutes,
    :user,
    :volumes
  ]

  @type t :: %__MODULE__{
          :autoArchiveInterval => integer() | nil,
          :autoDeleteInterval => integer() | nil,
          :autoPauseInterval => integer() | nil,
          :autoStopInterval => integer() | nil,
          :buildInfo => ExDaytona.Model.CreateBuildInfo.t() | nil,
          :cpu => integer() | nil,
          :disk => integer() | nil,
          :domainAllowList => String.t() | nil,
          :env => %{optional(String.t()) => String.t()} | nil,
          :gpu => integer() | nil,
          :gpuType => [ExDaytona.Model.GpuType.t()] | nil,
          :labels => %{optional(String.t()) => String.t()} | nil,
          :linkedSandbox => String.t() | nil,
          :memory => integer() | nil,
          :name => String.t() | nil,
          :networkAllowList => String.t() | nil,
          :networkBlockAll => boolean() | nil,
          :otelEndpointOverride => String.t() | nil,
          :outboundProxyUrl => String.t() | nil,
          :public => boolean() | nil,
          :secrets => [%{optional(String.t()) => String.t()}] | nil,
          :snapshot => String.t() | nil,
          :spot => boolean() | nil,
          :target => String.t() | nil,
          :ttlMinutes => integer() | nil,
          :user => String.t() | nil,
          :volumes => [ExDaytona.Model.SandboxVolume.t()] | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:buildInfo, :struct, ExDaytona.Model.CreateBuildInfo)
    |> Deserializer.deserialize(:gpuType, :list, ExDaytona.Model.GpuType)
    |> Deserializer.deserialize(:volumes, :list, ExDaytona.Model.SandboxVolume)
  end
end
