# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.CreateUser do
  @moduledoc """
  CreateUser model.
  """

  @derive JSON.Encoder
  defstruct [
    :email,
    :emailVerified,
    :emailVerifiedSource,
    :id,
    :name,
    :personalOrganizationDefaultRegionId,
    :personalOrganizationQuota,
    :role
  ]

  @type t :: %__MODULE__{
          :email => String.t() | nil,
          :emailVerified => boolean() | nil,
          :emailVerifiedSource => String.t() | nil,
          :id => String.t() | nil,
          :name => String.t(),
          :personalOrganizationDefaultRegionId => String.t() | nil,
          :personalOrganizationQuota => ExDaytona.Model.CreateOrganizationQuota.t() | nil,
          :role => String.t() | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:personalOrganizationQuota, :struct, ExDaytona.Model.CreateOrganizationQuota)
  end
end
