# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.DateFilter do
  @moduledoc """
  DateFilter model.
  """

  @derive JSON.Encoder
  defstruct [
    :gt,
    :gte,
    :lt,
    :lte
  ]

  @type t :: %__MODULE__{
          :gt => DateTime.t() | nil,
          :gte => DateTime.t() | nil,
          :lt => DateTime.t() | nil,
          :lte => DateTime.t() | nil
        }

  def decode(value) do
    value
  end
end
