# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.DaytonaConfiguration do
  @moduledoc """
  DaytonaConfiguration model.
  """

  @derive JSON.Encoder
  defstruct [
    :analyticsApiUrl,
    :announcements,
    :billingApiUrl,
    :buildSha,
    :dashboardUrl,
    :defaultSnapshot,
    :environment,
    :forcedFeatureFlags,
    :linkedAccountsEnabled,
    :maintananceMode,
    :maxAutoArchiveInterval,
    :oidc,
    :posthog,
    :proxyTemplateUrl,
    :proxyToolboxUrl,
    :pylonAppId,
    :rateLimit,
    :sshGatewayCommand,
    :sshGatewayPublicKey,
    :ssoOidc,
    :stripePublishableKey,
    :version
  ]

  @type t :: %__MODULE__{
          :analyticsApiUrl => String.t() | nil,
          :announcements => %{optional(String.t()) => ExDaytona.Model.Announcement.t()},
          :billingApiUrl => String.t() | nil,
          :buildSha => String.t() | nil,
          :dashboardUrl => String.t(),
          :defaultSnapshot => String.t(),
          :environment => String.t(),
          :forcedFeatureFlags => [String.t()] | nil,
          :linkedAccountsEnabled => boolean(),
          :maintananceMode => boolean(),
          :maxAutoArchiveInterval => number(),
          :oidc => ExDaytona.Model.OidcConfig.t(),
          :posthog => ExDaytona.Model.PosthogConfig.t() | nil,
          :proxyTemplateUrl => String.t(),
          :proxyToolboxUrl => String.t(),
          :pylonAppId => String.t() | nil,
          :rateLimit => ExDaytona.Model.RateLimitConfig.t() | nil,
          :sshGatewayCommand => String.t() | nil,
          :sshGatewayPublicKey => String.t() | nil,
          :ssoOidc => ExDaytona.Model.SsoOidcConfig.t() | nil,
          :stripePublishableKey => String.t() | nil,
          :version => String.t()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:announcements, :map, ExDaytona.Model.Announcement)
    |> Deserializer.deserialize(:oidc, :struct, ExDaytona.Model.OidcConfig)
    |> Deserializer.deserialize(:posthog, :struct, ExDaytona.Model.PosthogConfig)
    |> Deserializer.deserialize(:rateLimit, :struct, ExDaytona.Model.RateLimitConfig)
    |> Deserializer.deserialize(:ssoOidc, :struct, ExDaytona.Model.SsoOidcConfig)
  end
end
