# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.DockerRegistry do
  @moduledoc """
  DockerRegistry model.
  """

  @derive JSON.Encoder
  defstruct [
    :createdAt,
    :id,
    :name,
    :project,
    :registryType,
    :updatedAt,
    :url,
    :username
  ]

  @type t :: %__MODULE__{
          :createdAt => DateTime.t(),
          :id => String.t(),
          :name => String.t(),
          :project => String.t(),
          :registryType => String.t(),
          :updatedAt => DateTime.t(),
          :url => String.t(),
          :username => String.t()
        }

  def decode(value) do
    value
  end
end
