# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.ErrorResponse do
  @moduledoc """
  Error response
  """

  @derive JSON.Encoder
  defstruct [
    :code,
    :message,
    :method,
    :path,
    :source,
    :statusCode,
    :timestamp
  ]

  @type t :: %__MODULE__{
          :code => ExDaytona.Model.DaemonErrorCode.t() | nil,
          :message => String.t(),
          :method => String.t() | nil,
          :path => String.t(),
          :source => String.t() | nil,
          :statusCode => integer(),
          :timestamp => String.t()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:code, :struct, ExDaytona.Model.DaemonErrorCode)
  end
end
