# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.FileInfo do
  @moduledoc """
  FileInfo model.
  """

  @derive JSON.Encoder
  defstruct [
    :group,
    :isDir,
    :modTime,
    :mode,
    :modifiedAt,
    :name,
    :owner,
    :path,
    :permissions,
    :size
  ]

  @type t :: %__MODULE__{
          :group => String.t(),
          :isDir => boolean(),
          :modTime => String.t(),
          :mode => String.t(),
          :modifiedAt => String.t(),
          :name => String.t(),
          :owner => String.t(),
          :path => String.t() | nil,
          :permissions => String.t(),
          :size => integer()
        }

  def decode(value) do
    value
  end
end
