# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.FileStatus do
  @moduledoc """
  FileStatus model.
  """

  @derive JSON.Encoder
  defstruct [
    :extra,
    :name,
    :staging,
    :worktree
  ]

  @type t :: %__MODULE__{
          :extra => String.t(),
          :name => String.t(),
          :staging => ExDaytona.Model.Status.t(),
          :worktree => ExDaytona.Model.Status.t()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:staging, :struct, ExDaytona.Model.Status)
    |> Deserializer.deserialize(:worktree, :struct, ExDaytona.Model.Status)
  end
end
