# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.FindAccessibilityNodesRequest do
  @moduledoc """
  FindAccessibilityNodesRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :limit,
    :name,
    :nameMatch,
    :pid,
    :role,
    :scope,
    :states
  ]

  @type t :: %__MODULE__{
          :limit => integer() | nil,
          :name => String.t() | nil,
          :nameMatch => String.t() | nil,
          :pid => integer() | nil,
          :role => String.t() | nil,
          :scope => String.t() | nil,
          :states => [String.t()] | nil
        }

  def decode(value) do
    value
  end
end
