# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.GitPullRequest do
  @moduledoc """
  GitPullRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :branch,
    :password,
    :path,
    :remote,
    :username
  ]

  @type t :: %__MODULE__{
          :branch => String.t() | nil,
          :password => String.t() | nil,
          :path => String.t(),
          :remote => String.t() | nil,
          :username => String.t() | nil
        }

  def decode(value) do
    value
  end
end
