# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.GitInitRequest do
  @moduledoc """
  GitInitRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :bare,
    :initial_branch,
    :path
  ]

  @type t :: %__MODULE__{
          :bare => boolean() | nil,
          :initial_branch => String.t() | nil,
          :path => String.t()
        }

  def decode(value) do
    value
  end
end
