# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.GitAddRemoteRequest do
  @moduledoc """
  GitAddRemoteRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :fetch,
    :name,
    :overwrite,
    :path,
    :url
  ]

  @type t :: %__MODULE__{
          :fetch => boolean() | nil,
          :name => String.t(),
          :overwrite => boolean() | nil,
          :path => String.t(),
          :url => String.t()
        }

  def decode(value) do
    value
  end
end
