# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.GitConfigureUserRequest do
  @moduledoc """
  GitConfigureUserRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :email,
    :name,
    :path,
    :scope
  ]

  @type t :: %__MODULE__{
          :email => String.t(),
          :name => String.t(),
          :path => String.t() | nil,
          :scope => String.t() | nil
        }

  def decode(value) do
    value
  end
end
