# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.GitCloneRequest do
  @moduledoc """
  GitCloneRequest model.
  """

  # Encode without nil fields: unset optional fields must be OMITTED from
  # request JSON, not sent as explicit nulls — real servers (Daytona
  # included) reject bodies full of nulls that a bare {} would satisfy.
  defimpl JSON.Encoder do
    def encode(struct, encoder) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_field, value} -> is_nil(value) end)
      |> Map.new()
      |> encoder.(encoder)
    end
  end

  defstruct [
    :branch,
    :commit_id,
    :depth,
    :insecure_skip_tls,
    :password,
    :path,
    :url,
    :username
  ]

  @type t :: %__MODULE__{
          :branch => String.t() | nil,
          :commit_id => String.t() | nil,
          :depth => integer() | nil,
          :insecure_skip_tls => boolean() | nil,
          :password => String.t() | nil,
          :path => String.t(),
          :url => String.t(),
          :username => String.t() | nil
        }

  def decode(value) do
    value
  end
end
