# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.GitStatus do
  @moduledoc """
  GitStatus model.
  """

  @derive JSON.Encoder
  defstruct [
    :ahead,
    :behind,
    :branchPublished,
    :currentBranch,
    :detached,
    :fileStatus,
    :upstream
  ]

  @type t :: %__MODULE__{
          :ahead => integer() | nil,
          :behind => integer() | nil,
          :branchPublished => boolean() | nil,
          :currentBranch => String.t(),
          :detached => boolean() | nil,
          :fileStatus => [ExDaytona.Model.FileStatus.t()],
          :upstream => String.t() | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:fileStatus, :list, ExDaytona.Model.FileStatus)
  end
end
