# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.HealthControllerCheck200Response do
  @moduledoc """
  HealthControllerCheck200Response model.
  """

  @derive JSON.Encoder
  defstruct [
    :details,
    :error,
    :info,
    :status
  ]

  @type t :: %__MODULE__{
          :details => %{optional(String.t()) => ExDaytona.Model.HealthControllerCheck200ResponseDetailsValue.t()} | nil,
          :error => %{optional(String.t()) => ExDaytona.Model.HealthControllerCheck200ResponseDetailsValue.t()} | nil,
          :info => %{optional(String.t()) => ExDaytona.Model.HealthControllerCheck200ResponseDetailsValue.t()} | nil,
          :status => String.t() | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:details, :map, ExDaytona.Model.HealthControllerCheck200ResponseDetailsValue)
    |> Deserializer.deserialize(:error, :map, ExDaytona.Model.HealthControllerCheck200ResponseDetailsValue)
    |> Deserializer.deserialize(:info, :map, ExDaytona.Model.HealthControllerCheck200ResponseDetailsValue)
  end
end
