# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.IdentityProvider do
  @moduledoc """
  IdentityProvider model.
  """

  @derive JSON.Encoder
  defstruct [
    :allowAnyDomain,
    :createdAt,
    :defaultAssignedRoleIds,
    :emailDomains,
    :enabled,
    :id,
    :name,
    :oidcConfig,
    :organizationId,
    :trustEmailVerified,
    :updatedAt
  ]

  @type t :: %__MODULE__{
          :allowAnyDomain => boolean(),
          :createdAt => DateTime.t(),
          :defaultAssignedRoleIds => [String.t()],
          :emailDomains => [String.t()],
          :enabled => boolean(),
          :id => String.t(),
          :name => String.t(),
          :oidcConfig => ExDaytona.Model.OidcIdPConfigResponse.t(),
          :organizationId => String.t(),
          :trustEmailVerified => boolean(),
          :updatedAt => DateTime.t()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:oidcConfig, :struct, ExDaytona.Model.OidcIdPConfigResponse)
  end
end
