# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.IntFilter do
  @moduledoc """
  IntFilter model.
  """

  @derive JSON.Encoder
  defstruct [
    :eq,
    :gt,
    :gte,
    :in,
    :lt,
    :lte,
    :not,
    :notIn
  ]

  @type t :: %__MODULE__{
          :eq => number() | nil,
          :gt => number() | nil,
          :gte => number() | nil,
          :in => [number()] | nil,
          :lt => number() | nil,
          :lte => number() | nil,
          :not => number() | nil,
          :notIn => [number()] | nil
        }

  def decode(value) do
    value
  end
end
