# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.Job do
  @moduledoc """
  Job model.
  """

  @derive JSON.Encoder
  defstruct [
    :createdAt,
    :errorMessage,
    :id,
    :payload,
    :resourceId,
    :resourceType,
    :status,
    :traceContext,
    :type,
    :updatedAt
  ]

  @type t :: %__MODULE__{
          :createdAt => String.t(),
          :errorMessage => String.t() | nil,
          :id => String.t(),
          :payload => String.t() | nil,
          :resourceId => String.t(),
          :resourceType => String.t(),
          :status => ExDaytona.Model.JobStatus.t(),
          :traceContext => %{optional(String.t()) => any()} | nil,
          :type => ExDaytona.Model.JobType.t(),
          :updatedAt => String.t() | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:status, :struct, ExDaytona.Model.JobStatus)
    |> Deserializer.deserialize(:type, :struct, ExDaytona.Model.JobType)
  end
end
