# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.KeyboardHotkeyRequest do
  @moduledoc """
  KeyboardHotkeyRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :keys
  ]

  @type t :: %__MODULE__{
          :keys => String.t() | nil
        }

  def decode(value) do
    value
  end
end
