# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.ListContextsResponse do
  @moduledoc """
  ListContextsResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :contexts
  ]

  @type t :: %__MODULE__{
          :contexts => [ExDaytona.Model.InterpreterContext.t()]
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:contexts, :list, ExDaytona.Model.InterpreterContext)
  end
end
