# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.ListRemotesResponse do
  @moduledoc """
  ListRemotesResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :remotes
  ]

  @type t :: %__MODULE__{
          :remotes => [ExDaytona.Model.GitRemote.t()]
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:remotes, :list, ExDaytona.Model.GitRemote)
  end
end
