# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.ListRecordingsResponse do
  @moduledoc """
  ListRecordingsResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :recordings
  ]

  @type t :: %__MODULE__{
          :recordings => [ExDaytona.Model.Recording.t()]
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:recordings, :list, ExDaytona.Model.Recording)
  end
end
