# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.LogEntry do
  @moduledoc """
  LogEntry model.
  """

  @derive JSON.Encoder
  defstruct [
    :body,
    :logAttributes,
    :resourceAttributes,
    :serviceName,
    :severityNumber,
    :severityText,
    :spanId,
    :timestamp,
    :traceId
  ]

  @type t :: %__MODULE__{
          :body => String.t(),
          :logAttributes => %{optional(String.t()) => String.t()},
          :resourceAttributes => %{optional(String.t()) => String.t()},
          :serviceName => String.t(),
          :severityNumber => number() | nil,
          :severityText => String.t(),
          :spanId => String.t() | nil,
          :timestamp => String.t(),
          :traceId => String.t() | nil
        }

  def decode(value) do
    value
  end
end
