# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.LspLocation do
  @moduledoc """
  LspLocation model.
  """

  @derive JSON.Encoder
  defstruct [
    :range,
    :uri
  ]

  @type t :: %__MODULE__{
          :range => ExDaytona.Model.LspRange.t(),
          :uri => String.t()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:range, :struct, ExDaytona.Model.LspRange)
  end
end
