# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.MetricsResponse do
  @moduledoc """
  MetricsResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :series
  ]

  @type t :: %__MODULE__{
          :series => [ExDaytona.Model.MetricSeries.t()]
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:series, :list, ExDaytona.Model.MetricSeries)
  end
end
