# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.ModelsAggregatedUsage do
  @moduledoc """
  ModelsAggregatedUsage model.
  """

  # Credential-safe inspection: fields whose names indicate credentials
  # (tokens, keys, secrets, passwords) render as "[REDACTED]" — see
  # ExDaytona.Redact. Regeneration cannot remove this protection
  # because it lives in the model template.
  defimpl Inspect do
    def inspect(struct, opts), do: ExDaytona.Redact.inspect_struct(struct, opts)
  end

  # Encode without nil fields: unset optional fields must be OMITTED from
  # request JSON, not sent as explicit nulls — real servers (Daytona
  # included) reject bodies full of nulls that a bare {} would satisfy.
  defimpl JSON.Encoder do
    def encode(struct, encoder) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_field, value} -> is_nil(value) end)
      |> Map.new()
      |> encoder.(encoder)
    end
  end

  defstruct [
    :firstStart,
    :lastEnd,
    :sandboxCount,
    :totalCPUSeconds,
    :totalDiskGBSeconds,
    :totalGPUSeconds,
    :totalPrice,
    :totalRAMGBSeconds
  ]

  @type t :: %__MODULE__{
          :firstStart => String.t() | nil,
          :lastEnd => String.t() | nil,
          :sandboxCount => integer() | nil,
          :totalCPUSeconds => integer() | nil,
          :totalDiskGBSeconds => integer() | nil,
          :totalGPUSeconds => integer() | nil,
          :totalPrice => number() | nil,
          :totalRAMGBSeconds => integer() | nil
        }

  def decode(value) do
    value
  end
end
