# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.ModelsUsagePeriod do
  @moduledoc """
  ModelsUsagePeriod model.
  """

  @derive JSON.Encoder
  defstruct [
    :cpu,
    :diskGB,
    :endAt,
    :gpu,
    :price,
    :ramGB,
    :startAt
  ]

  @type t :: %__MODULE__{
          :cpu => integer() | nil,
          :diskGB => integer() | nil,
          :endAt => String.t() | nil,
          :gpu => integer() | nil,
          :price => number() | nil,
          :ramGB => integer() | nil,
          :startAt => String.t() | nil
        }

  def decode(value) do
    value
  end
end
