# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.ModelsTraceSummary do
  @moduledoc """
  ModelsTraceSummary model.
  """

  @derive JSON.Encoder
  defstruct [
    :endTime,
    :rootSpanName,
    :spanCount,
    :startTime,
    :statusCode,
    :totalDurationMs,
    :traceId
  ]

  @type t :: %__MODULE__{
          :endTime => String.t() | nil,
          :rootSpanName => String.t() | nil,
          :spanCount => integer() | nil,
          :startTime => String.t() | nil,
          :statusCode => String.t() | nil,
          :totalDurationMs => number() | nil,
          :traceId => String.t() | nil
        }

  def decode(value) do
    value
  end
end
