# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.ModelsSandboxUsage do
  @moduledoc """
  ModelsSandboxUsage model.
  """

  @derive JSON.Encoder
  defstruct [
    :firstStart,
    :lastEnd,
    :sandboxId,
    :totalCPUSeconds,
    :totalDiskGBSeconds,
    :totalGPUSeconds,
    :totalPrice,
    :totalRAMGBSeconds
  ]

  @type t :: %__MODULE__{
          :firstStart => String.t() | nil,
          :lastEnd => String.t() | nil,
          :sandboxId => String.t() | nil,
          :totalCPUSeconds => integer() | nil,
          :totalDiskGBSeconds => integer() | nil,
          :totalGPUSeconds => integer() | nil,
          :totalPrice => number() | nil,
          :totalRAMGBSeconds => integer() | nil
        }

  def decode(value) do
    value
  end
end
