# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.ModelsLogEntry do
  @moduledoc """
  ModelsLogEntry model.
  """

  # Encode without nil fields: unset optional fields must be OMITTED from
  # request JSON, not sent as explicit nulls — real servers (Daytona
  # included) reject bodies full of nulls that a bare {} would satisfy.
  defimpl JSON.Encoder do
    def encode(struct, encoder) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_field, value} -> is_nil(value) end)
      |> Map.new()
      |> encoder.(encoder)
    end
  end

  defstruct [
    :body,
    :logAttributes,
    :resourceAttributes,
    :serviceName,
    :severityNumber,
    :severityText,
    :spanId,
    :timestamp,
    :traceId
  ]

  @type t :: %__MODULE__{
          :body => String.t() | nil,
          :logAttributes => %{optional(String.t()) => String.t()} | nil,
          :resourceAttributes => %{optional(String.t()) => String.t()} | nil,
          :serviceName => String.t() | nil,
          :severityNumber => integer() | nil,
          :severityText => String.t() | nil,
          :spanId => String.t() | nil,
          :timestamp => String.t() | nil,
          :traceId => String.t() | nil
        }

  def decode(value) do
    value
  end
end
