# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.MouseScrollRequest do
  @moduledoc """
  MouseScrollRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :amount,
    :direction,
    :x,
    :y
  ]

  @type t :: %__MODULE__{
          :amount => integer() | nil,
          :direction => String.t() | nil,
          :x => integer() | nil,
          :y => integer() | nil
        }

  def decode(value) do
    value
  end
end
