# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.MouseDragRequest do
  @moduledoc """
  MouseDragRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :button,
    :endX,
    :endY,
    :startX,
    :startY
  ]

  @type t :: %__MODULE__{
          :button => String.t() | nil,
          :endX => integer() | nil,
          :endY => integer() | nil,
          :startX => integer() | nil,
          :startY => integer() | nil
        }

  def decode(value) do
    value
  end
end
