# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.OidcIdPConfig do
  @moduledoc """
  OidcIdPConfig model.
  """

  @derive JSON.Encoder
  defstruct [
    :clientId,
    :clientSecret,
    :issuerUrl,
    :scope
  ]

  @type t :: %__MODULE__{
          :clientId => String.t(),
          :clientSecret => String.t(),
          :issuerUrl => String.t(),
          :scope => String.t() | nil
        }

  def decode(value) do
    value
  end
end
