# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.OrganizationPreviewWarning do
  @moduledoc """
  OrganizationPreviewWarning model.
  """

  @derive JSON.Encoder
  defstruct [
    :previewWarningEnabled
  ]

  @type t :: %__MODULE__{
          :previewWarningEnabled => boolean()
        }

  def decode(value) do
    value
  end
end
