# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.OrganizationUsageOverview do
  @moduledoc """
  OrganizationUsageOverview model.
  """

  @derive JSON.Encoder
  defstruct [
    :currentSnapshotUsage,
    :currentVolumeUsage,
    :regionUsage,
    :totalSnapshotQuota,
    :totalVolumeQuota
  ]

  @type t :: %__MODULE__{
          :currentSnapshotUsage => number(),
          :currentVolumeUsage => number(),
          :regionUsage => [ExDaytona.Model.RegionUsageOverview.t()],
          :totalSnapshotQuota => number(),
          :totalVolumeQuota => number()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:regionUsage, :list, ExDaytona.Model.RegionUsageOverview)
  end
end
