# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.OrganizationSuspension do
  @moduledoc """
  OrganizationSuspension model.
  """

  @derive JSON.Encoder
  defstruct [
    :reason,
    :suspensionCleanupGracePeriodHours,
    :until
  ]

  @type t :: %__MODULE__{
          :reason => String.t(),
          :suspensionCleanupGracePeriodHours => number() | nil,
          :until => DateTime.t()
        }

  def decode(value) do
    value
  end
end
