# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.OrganizationUser do
  @moduledoc """
  OrganizationUser model.
  """

  @derive JSON.Encoder
  defstruct [
    :assignedRoles,
    :createdAt,
    :email,
    :name,
    :organizationId,
    :role,
    :updatedAt,
    :userId
  ]

  @type t :: %__MODULE__{
          :assignedRoles => [ExDaytona.Model.OrganizationRole.t()],
          :createdAt => DateTime.t(),
          :email => String.t(),
          :name => String.t(),
          :organizationId => String.t(),
          :role => String.t(),
          :updatedAt => DateTime.t(),
          :userId => String.t()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:assignedRoles, :list, ExDaytona.Model.OrganizationRole)
  end
end
