# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.Organization do
  @moduledoc """
  Organization model.
  """

  # Credential-safe inspection: fields whose names indicate credentials
  # (tokens, keys, secrets, passwords) render as "[REDACTED]" — see
  # ExDaytona.Redact. Regeneration cannot remove this protection
  # because it lives in the model template.
  defimpl Inspect do
    def inspect(struct, opts), do: ExDaytona.Redact.inspect_struct(struct, opts)
  end

  # Encode without nil fields: unset optional fields must be OMITTED from
  # request JSON, not sent as explicit nulls — real servers (Daytona
  # included) reject bodies full of nulls that a bare {} would satisfy.
  defimpl JSON.Encoder do
    def encode(struct, encoder) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_field, value} -> is_nil(value) end)
      |> Map.new()
      |> encoder.(encoder)
    end
  end

  defstruct [
    :authenticatedRateLimit,
    :authenticatedRateLimitTtlSeconds,
    :createdAt,
    :createdBy,
    :defaultRegionId,
    :experimentalConfig,
    :id,
    :maxCpuPerSandbox,
    :maxDiskPerSandbox,
    :maxMemoryPerSandbox,
    :maxSecretsPerSandbox,
    :name,
    :otelConfig,
    :personal,
    :previewWarningEnabled,
    :sandboxCreateRateLimit,
    :sandboxCreateRateLimitTtlSeconds,
    :sandboxLifecycleRateLimit,
    :sandboxLifecycleRateLimitTtlSeconds,
    :sandboxLimitedNetworkEgress,
    :secretQuota,
    :snapshotDeactivationTimeoutMinutes,
    :ssoEnabled,
    :suspended,
    :suspendedAt,
    :suspendedUntil,
    :suspensionCleanupGracePeriodHours,
    :suspensionReason,
    :updatedAt
  ]

  @type t :: %__MODULE__{
          :authenticatedRateLimit => number() | nil,
          :authenticatedRateLimitTtlSeconds => number() | nil,
          :createdAt => DateTime.t(),
          :createdBy => String.t(),
          :defaultRegionId => String.t() | nil,
          :experimentalConfig => map(),
          :id => String.t(),
          :maxCpuPerSandbox => number(),
          :maxDiskPerSandbox => number(),
          :maxMemoryPerSandbox => number(),
          :maxSecretsPerSandbox => number(),
          :name => String.t(),
          :otelConfig => ExDaytona.Model.OtelConfig.t() | nil,
          :personal => boolean(),
          :previewWarningEnabled => boolean(),
          :sandboxCreateRateLimit => number() | nil,
          :sandboxCreateRateLimitTtlSeconds => number() | nil,
          :sandboxLifecycleRateLimit => number() | nil,
          :sandboxLifecycleRateLimitTtlSeconds => number() | nil,
          :sandboxLimitedNetworkEgress => boolean(),
          :secretQuota => number(),
          :snapshotDeactivationTimeoutMinutes => number(),
          :ssoEnabled => boolean(),
          :suspended => boolean(),
          :suspendedAt => DateTime.t(),
          :suspendedUntil => DateTime.t(),
          :suspensionCleanupGracePeriodHours => number(),
          :suspensionReason => String.t(),
          :updatedAt => DateTime.t()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:otelConfig, :struct, ExDaytona.Model.OtelConfig)
  end
end
