# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.OrganizationUsageOverview do
  @moduledoc """
  OrganizationUsageOverview model.
  """

  # Credential-safe inspection: fields whose names indicate credentials
  # (tokens, keys, secrets, passwords) render as "[REDACTED]" — see
  # ExDaytona.Redact. Regeneration cannot remove this protection
  # because it lives in the model template.
  defimpl Inspect do
    def inspect(struct, opts), do: ExDaytona.Redact.inspect_struct(struct, opts)
  end

  # Encode without nil fields: unset optional fields must be OMITTED from
  # request JSON, not sent as explicit nulls — real servers (Daytona
  # included) reject bodies full of nulls that a bare {} would satisfy.
  defimpl JSON.Encoder do
    def encode(struct, encoder) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_field, value} -> is_nil(value) end)
      |> Map.new()
      |> encoder.(encoder)
    end
  end

  defstruct [
    :currentSnapshotUsage,
    :currentVolumeUsage,
    :regionUsage,
    :totalSnapshotQuota,
    :totalVolumeQuota
  ]

  @type t :: %__MODULE__{
          :currentSnapshotUsage => number(),
          :currentVolumeUsage => number(),
          :regionUsage => [ExDaytona.Model.RegionUsageOverview.t()],
          :totalSnapshotQuota => number(),
          :totalVolumeQuota => number()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:regionUsage, :list, ExDaytona.Model.RegionUsageOverview)
  end
end
