# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.OtelConfig do
  @moduledoc """
  OtelConfig model.
  """

  @derive JSON.Encoder
  defstruct [
    :endpoint,
    :headers,
    :organizationId
  ]

  @type t :: %__MODULE__{
          :endpoint => String.t(),
          :headers => %{optional(String.t()) => String.t()} | nil,
          :organizationId => String.t() | nil
        }

  def decode(value) do
    value
  end
end
