# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.PaginatedLogs do
  @moduledoc """
  PaginatedLogs model.
  """

  @derive JSON.Encoder
  defstruct [
    :items,
    :page,
    :total,
    :totalPages
  ]

  @type t :: %__MODULE__{
          :items => [ExDaytona.Model.LogEntry.t()],
          :page => number(),
          :total => number(),
          :totalPages => number()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:items, :list, ExDaytona.Model.LogEntry)
  end
end
