# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.PollJobsResponse do
  @moduledoc """
  PollJobsResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :jobs
  ]

  @type t :: %__MODULE__{
          :jobs => [ExDaytona.Model.Job.t()]
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:jobs, :list, ExDaytona.Model.Job)
  end
end
