# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.PtyCreateRequest do
  @moduledoc """
  PtyCreateRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :cols,
    :cwd,
    :envs,
    :id,
    :lazyStart,
    :rows
  ]

  @type t :: %__MODULE__{
          :cols => integer() | nil,
          :cwd => String.t() | nil,
          :envs => %{optional(String.t()) => String.t()} | nil,
          :id => String.t() | nil,
          :lazyStart => boolean() | nil,
          :rows => integer() | nil
        }

  def decode(value) do
    value
  end
end
