# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.PtySessionInfo do
  @moduledoc """
  PtySessionInfo model.
  """

  @derive JSON.Encoder
  defstruct [
    :active,
    :cols,
    :createdAt,
    :cwd,
    :envs,
    :id,
    :lazyStart,
    :rows
  ]

  @type t :: %__MODULE__{
          :active => boolean(),
          :cols => integer(),
          :createdAt => String.t(),
          :cwd => String.t(),
          :envs => %{optional(String.t()) => String.t()},
          :id => String.t(),
          :lazyStart => boolean(),
          :rows => integer()
        }

  def decode(value) do
    value
  end
end
