# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.RateLimitConfig do
  @moduledoc """
  RateLimitConfig model.
  """

  @derive JSON.Encoder
  defstruct [
    :authenticated,
    :failedAuth,
    :sandboxCreate,
    :sandboxLifecycle,
    :sandboxList
  ]

  @type t :: %__MODULE__{
          :authenticated => ExDaytona.Model.RateLimitEntry.t() | nil,
          :failedAuth => ExDaytona.Model.RateLimitEntry.t() | nil,
          :sandboxCreate => ExDaytona.Model.RateLimitEntry.t() | nil,
          :sandboxLifecycle => ExDaytona.Model.RateLimitEntry.t() | nil,
          :sandboxList => ExDaytona.Model.RateLimitEntry.t() | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:authenticated, :struct, ExDaytona.Model.RateLimitEntry)
    |> Deserializer.deserialize(:failedAuth, :struct, ExDaytona.Model.RateLimitEntry)
    |> Deserializer.deserialize(:sandboxCreate, :struct, ExDaytona.Model.RateLimitEntry)
    |> Deserializer.deserialize(:sandboxLifecycle, :struct, ExDaytona.Model.RateLimitEntry)
    |> Deserializer.deserialize(:sandboxList, :struct, ExDaytona.Model.RateLimitEntry)
  end
end
