# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.Recording do
  @moduledoc """
  Recording model.
  """

  @derive JSON.Encoder
  defstruct [
    :durationSeconds,
    :endTime,
    :fileName,
    :filePath,
    :id,
    :sizeBytes,
    :startTime,
    :status
  ]

  @type t :: %__MODULE__{
          :durationSeconds => number() | nil,
          :endTime => String.t() | nil,
          :fileName => String.t(),
          :filePath => String.t(),
          :id => String.t(),
          :sizeBytes => integer() | nil,
          :startTime => String.t(),
          :status => String.t()
        }

  def decode(value) do
    value
  end
end
