# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.Region do
  @moduledoc """
  Region model.
  """

  @derive JSON.Encoder
  defstruct [
    :createdAt,
    :id,
    :name,
    :organizationId,
    :otelEndpoint,
    :proxyUrl,
    :regionType,
    :snapshotManagerUrl,
    :sshGatewayUrl,
    :updatedAt
  ]

  @type t :: %__MODULE__{
          :createdAt => String.t(),
          :id => String.t(),
          :name => String.t(),
          :organizationId => String.t() | nil,
          :otelEndpoint => String.t() | nil,
          :proxyUrl => String.t() | nil,
          :regionType => ExDaytona.Model.RegionType.t(),
          :snapshotManagerUrl => String.t() | nil,
          :sshGatewayUrl => String.t() | nil,
          :updatedAt => String.t()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:regionType, :struct, ExDaytona.Model.RegionType)
  end
end
