# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.RegistryPushAccessDto do
  @moduledoc """
  RegistryPushAccessDto model.
  """

  @derive JSON.Encoder
  defstruct [
    :expiresAt,
    :project,
    :registryId,
    :registryUrl,
    :secret,
    :username
  ]

  @type t :: %__MODULE__{
          :expiresAt => String.t(),
          :project => String.t(),
          :registryId => String.t(),
          :registryUrl => String.t(),
          :secret => String.t(),
          :username => String.t()
        }

  def decode(value) do
    value
  end
end
