# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.ResizeSandbox do
  @moduledoc """
  ResizeSandbox model.
  """

  @derive JSON.Encoder
  defstruct [
    :cpu,
    :disk,
    :memory
  ]

  @type t :: %__MODULE__{
          :cpu => integer() | nil,
          :disk => integer() | nil,
          :memory => integer() | nil
        }

  def decode(value) do
    value
  end
end
