# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.ResolveSandboxSecrets200ResponseInner do
  @moduledoc """
  ResolveSandboxSecrets200ResponseInner model.
  """

  @derive JSON.Encoder
  defstruct [
    :env,
    :hosts,
    :placeholder,
    :value
  ]

  @type t :: %__MODULE__{
          :env => String.t() | nil,
          :hosts => [String.t()] | nil,
          :placeholder => String.t() | nil,
          :value => String.t() | nil
        }

  def decode(value) do
    value
  end
end
