# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.RunnerHealthMetrics do
  @moduledoc """
  RunnerHealthMetrics model.
  """

  @derive JSON.Encoder
  defstruct [
    :cpu,
    :currentAllocatedCpu,
    :currentAllocatedDiskGiB,
    :currentAllocatedMemoryGiB,
    :currentCpuLoadAverage,
    :currentCpuUsagePercentage,
    :currentDiskUsagePercentage,
    :currentMemoryUsagePercentage,
    :currentSnapshotCount,
    :currentStartedSandboxes,
    :diskGiB,
    :gpu,
    :gpuType,
    :memoryGiB
  ]

  @type t :: %__MODULE__{
          :cpu => number(),
          :currentAllocatedCpu => number(),
          :currentAllocatedDiskGiB => number(),
          :currentAllocatedMemoryGiB => number(),
          :currentCpuLoadAverage => number(),
          :currentCpuUsagePercentage => number(),
          :currentDiskUsagePercentage => number(),
          :currentMemoryUsagePercentage => number(),
          :currentSnapshotCount => number(),
          :currentStartedSandboxes => number(),
          :diskGiB => number(),
          :gpu => number() | nil,
          :gpuType => String.t() | nil,
          :memoryGiB => number()
        }

  def decode(value) do
    value
  end
end
