# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.RunnerHealthcheck do
  @moduledoc """
  RunnerHealthcheck model.
  """

  # Encode without nil fields: unset optional fields must be OMITTED from
  # request JSON, not sent as explicit nulls — real servers (Daytona
  # included) reject bodies full of nulls that a bare {} would satisfy.
  defimpl JSON.Encoder do
    def encode(struct, encoder) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_field, value} -> is_nil(value) end)
      |> Map.new()
      |> encoder.(encoder)
    end
  end

  defstruct [
    :apiUrl,
    :appVersion,
    :domain,
    :metrics,
    :proxyUrl,
    :serviceHealth
  ]

  @type t :: %__MODULE__{
          :apiUrl => String.t() | nil,
          :appVersion => String.t(),
          :domain => String.t() | nil,
          :metrics => ExDaytona.Model.RunnerHealthMetrics.t() | nil,
          :proxyUrl => String.t() | nil,
          :serviceHealth => [ExDaytona.Model.RunnerServiceHealth.t()] | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:metrics, :struct, ExDaytona.Model.RunnerHealthMetrics)
    |> Deserializer.deserialize(:serviceHealth, :list, ExDaytona.Model.RunnerServiceHealth)
  end
end
