# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.RunnerFull do
  @moduledoc """
  RunnerFull model.
  """

  # Encode without nil fields: unset optional fields must be OMITTED from
  # request JSON, not sent as explicit nulls — real servers (Daytona
  # included) reject bodies full of nulls that a bare {} would satisfy.
  defimpl JSON.Encoder do
    def encode(struct, encoder) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_field, value} -> is_nil(value) end)
      |> Map.new()
      |> encoder.(encoder)
    end
  end

  defstruct [
    :apiKey,
    :apiUrl,
    :apiVersion,
    :appVersion,
    :availabilityScore,
    :class,
    :cpu,
    :createdAt,
    :currentAllocatedCpu,
    :currentAllocatedDiskGiB,
    :currentAllocatedMemoryGiB,
    :currentCpuUsagePercentage,
    :currentDiskUsagePercentage,
    :currentMemoryUsagePercentage,
    :currentSnapshotCount,
    :currentStartedSandboxes,
    :disk,
    :domain,
    :gpu,
    :gpuType,
    :id,
    :lastChecked,
    :memory,
    :name,
    :proxyUrl,
    :region,
    :regionType,
    :runnerClass,
    :sandboxClass,
    :state,
    :tags,
    :unschedulable,
    :updatedAt,
    :version
  ]

  @type t :: %__MODULE__{
          :apiKey => String.t(),
          :apiUrl => String.t() | nil,
          :apiVersion => String.t(),
          :appVersion => String.t() | nil,
          :availabilityScore => number() | nil,
          :class => String.t() | nil,
          :cpu => number(),
          :createdAt => String.t(),
          :currentAllocatedCpu => number() | nil,
          :currentAllocatedDiskGiB => number() | nil,
          :currentAllocatedMemoryGiB => number() | nil,
          :currentCpuUsagePercentage => number() | nil,
          :currentDiskUsagePercentage => number() | nil,
          :currentMemoryUsagePercentage => number() | nil,
          :currentSnapshotCount => number() | nil,
          :currentStartedSandboxes => number() | nil,
          :disk => number(),
          :domain => String.t() | nil,
          :gpu => number() | nil,
          :gpuType => String.t() | nil,
          :id => String.t(),
          :lastChecked => String.t() | nil,
          :memory => number(),
          :name => String.t(),
          :proxyUrl => String.t() | nil,
          :region => String.t(),
          :regionType => ExDaytona.Model.RegionType.t() | nil,
          :runnerClass => ExDaytona.Model.RunnerClass.t(),
          :sandboxClass => ExDaytona.Model.SandboxClass.t() | nil,
          :state => ExDaytona.Model.RunnerState.t(),
          :tags => [String.t()],
          :unschedulable => boolean(),
          :updatedAt => String.t(),
          :version => String.t()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:regionType, :struct, ExDaytona.Model.RegionType)
    |> Deserializer.deserialize(:runnerClass, :struct, ExDaytona.Model.RunnerClass)
    |> Deserializer.deserialize(:sandboxClass, :struct, ExDaytona.Model.SandboxClass)
    |> Deserializer.deserialize(:state, :struct, ExDaytona.Model.RunnerState)
  end
end
