# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.RunnerHealthcheck do
  @moduledoc """
  RunnerHealthcheck model.
  """

  @derive JSON.Encoder
  defstruct [
    :apiUrl,
    :appVersion,
    :domain,
    :metrics,
    :proxyUrl,
    :serviceHealth
  ]

  @type t :: %__MODULE__{
          :apiUrl => String.t() | nil,
          :appVersion => String.t(),
          :domain => String.t() | nil,
          :metrics => ExDaytona.Model.RunnerHealthMetrics.t() | nil,
          :proxyUrl => String.t() | nil,
          :serviceHealth => [ExDaytona.Model.RunnerServiceHealth.t()] | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:metrics, :struct, ExDaytona.Model.RunnerHealthMetrics)
    |> Deserializer.deserialize(:serviceHealth, :list, ExDaytona.Model.RunnerServiceHealth)
  end
end
