# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.RunnerHealthMetrics do
  @moduledoc """
  RunnerHealthMetrics model.
  """

  # Encode without nil fields: unset optional fields must be OMITTED from
  # request JSON, not sent as explicit nulls — real servers (Daytona
  # included) reject bodies full of nulls that a bare {} would satisfy.
  defimpl JSON.Encoder do
    def encode(struct, encoder) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_field, value} -> is_nil(value) end)
      |> Map.new()
      |> encoder.(encoder)
    end
  end

  defstruct [
    :cpu,
    :currentAllocatedCpu,
    :currentAllocatedDiskGiB,
    :currentAllocatedMemoryGiB,
    :currentCpuLoadAverage,
    :currentCpuUsagePercentage,
    :currentDiskUsagePercentage,
    :currentMemoryUsagePercentage,
    :currentSnapshotCount,
    :currentStartedSandboxes,
    :diskGiB,
    :gpu,
    :gpuType,
    :memoryGiB
  ]

  @type t :: %__MODULE__{
          :cpu => number(),
          :currentAllocatedCpu => number(),
          :currentAllocatedDiskGiB => number(),
          :currentAllocatedMemoryGiB => number(),
          :currentCpuLoadAverage => number(),
          :currentCpuUsagePercentage => number(),
          :currentDiskUsagePercentage => number(),
          :currentMemoryUsagePercentage => number(),
          :currentSnapshotCount => number(),
          :currentStartedSandboxes => number(),
          :diskGiB => number(),
          :gpu => number() | nil,
          :gpuType => String.t() | nil,
          :memoryGiB => number()
        }

  def decode(value) do
    value
  end
end
