# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.Sandbox do
  @moduledoc """
  Sandbox model.
  """

  # Encode without nil fields: unset optional fields must be OMITTED from
  # request JSON, not sent as explicit nulls — real servers (Daytona
  # included) reject bodies full of nulls that a bare {} would satisfy.
  defimpl JSON.Encoder do
    def encode(struct, encoder) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_field, value} -> is_nil(value) end)
      |> Map.new()
      |> encoder.(encoder)
    end
  end

  defstruct [
    :autoArchiveInterval,
    :autoDeleteInterval,
    :autoDestroyAt,
    :autoPauseInterval,
    :autoStopInterval,
    :backupCreatedAt,
    :backupState,
    :buildInfo,
    :cpu,
    :createdAt,
    :daemonVersion,
    :desiredState,
    :disk,
    :domainAllowList,
    :env,
    :errorReason,
    :gpu,
    :gpuType,
    :id,
    :labels,
    :lastActivityAt,
    :linkedSandboxId,
    :memory,
    :name,
    :networkAllowList,
    :networkBlockAll,
    :organizationId,
    :otelEndpointOverride,
    :outboundProxyUrl,
    :public,
    :recoverable,
    :runnerId,
    :sandboxClass,
    :snapshot,
    :spot,
    :spotEvictedAt,
    :state,
    :target,
    :toolboxProxyUrl,
    :updatedAt,
    :user,
    :volumes,
    :warmPoolId
  ]

  @type t :: %__MODULE__{
          :autoArchiveInterval => number() | nil,
          :autoDeleteInterval => number() | nil,
          :autoDestroyAt => String.t() | nil,
          :autoPauseInterval => number() | nil,
          :autoStopInterval => number() | nil,
          :backupCreatedAt => String.t() | nil,
          :backupState => String.t() | nil,
          :buildInfo => ExDaytona.Model.BuildInfo.t() | nil,
          :cpu => number(),
          :createdAt => String.t() | nil,
          :daemonVersion => String.t() | nil,
          :desiredState => ExDaytona.Model.SandboxDesiredState.t() | nil,
          :disk => number(),
          :domainAllowList => String.t() | nil,
          :env => %{optional(String.t()) => String.t()},
          :errorReason => String.t() | nil,
          :gpu => number(),
          :gpuType => ExDaytona.Model.GpuType.t() | nil,
          :id => String.t(),
          :labels => %{optional(String.t()) => String.t()},
          :lastActivityAt => String.t() | nil,
          :linkedSandboxId => String.t() | nil,
          :memory => number(),
          :name => String.t(),
          :networkAllowList => String.t() | nil,
          :networkBlockAll => boolean(),
          :organizationId => String.t(),
          :otelEndpointOverride => String.t() | nil,
          :outboundProxyUrl => String.t() | nil,
          :public => boolean(),
          :recoverable => boolean() | nil,
          :runnerId => String.t() | nil,
          :sandboxClass => String.t() | nil,
          :snapshot => String.t() | nil,
          :spot => boolean() | nil,
          :spotEvictedAt => String.t() | nil,
          :state => ExDaytona.Model.SandboxState.t() | nil,
          :target => String.t(),
          :toolboxProxyUrl => String.t(),
          :updatedAt => String.t() | nil,
          :user => String.t(),
          :volumes => [ExDaytona.Model.SandboxVolume.t()] | nil,
          :warmPoolId => String.t() | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:buildInfo, :struct, ExDaytona.Model.BuildInfo)
    |> Deserializer.deserialize(:desiredState, :struct, ExDaytona.Model.SandboxDesiredState)
    |> Deserializer.deserialize(:gpuType, :struct, ExDaytona.Model.GpuType)
    |> Deserializer.deserialize(:state, :struct, ExDaytona.Model.SandboxState)
    |> Deserializer.deserialize(:volumes, :list, ExDaytona.Model.SandboxVolume)
  end
end
