# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.SandboxListItem do
  @moduledoc """
  SandboxListItem model.
  """

  # Credential-safe inspection: fields whose names indicate credentials
  # (tokens, keys, secrets, passwords) render as "[REDACTED]" — see
  # ExDaytona.Redact. Regeneration cannot remove this protection
  # because it lives in the model template.
  defimpl Inspect do
    def inspect(struct, opts), do: ExDaytona.Redact.inspect_struct(struct, opts)
  end

  # Encode without nil fields: unset optional fields must be OMITTED from
  # request JSON, not sent as explicit nulls — real servers (Daytona
  # included) reject bodies full of nulls that a bare {} would satisfy.
  defimpl JSON.Encoder do
    def encode(struct, encoder) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_field, value} -> is_nil(value) end)
      |> Map.new()
      |> encoder.(encoder)
    end
  end

  defstruct [
    :autoArchiveInterval,
    :autoDeleteInterval,
    :autoDestroyAt,
    :autoPauseInterval,
    :autoStopInterval,
    :backupState,
    :cpu,
    :createdAt,
    :daemonVersion,
    :desiredState,
    :disk,
    :domainAllowList,
    :errorReason,
    :gpu,
    :gpuType,
    :id,
    :labels,
    :lastActivityAt,
    :memory,
    :name,
    :networkAllowList,
    :networkBlockAll,
    :organizationId,
    :public,
    :recoverable,
    :runnerId,
    :sandboxClass,
    :snapshot,
    :spot,
    :spotEvictedAt,
    :state,
    :target,
    :toolboxProxyUrl,
    :updatedAt,
    :user,
    :warmPoolId
  ]

  @type t :: %__MODULE__{
          :autoArchiveInterval => number() | nil,
          :autoDeleteInterval => number() | nil,
          :autoDestroyAt => String.t() | nil,
          :autoPauseInterval => number() | nil,
          :autoStopInterval => number() | nil,
          :backupState => String.t() | nil,
          :cpu => number(),
          :createdAt => String.t() | nil,
          :daemonVersion => String.t() | nil,
          :desiredState => ExDaytona.Model.SandboxDesiredState.t() | nil,
          :disk => number(),
          :domainAllowList => String.t() | nil,
          :errorReason => String.t() | nil,
          :gpu => number(),
          :gpuType => ExDaytona.Model.GpuType.t() | nil,
          :id => String.t(),
          :labels => %{optional(String.t()) => String.t()},
          :lastActivityAt => String.t() | nil,
          :memory => number(),
          :name => String.t(),
          :networkAllowList => String.t() | nil,
          :networkBlockAll => boolean(),
          :organizationId => String.t(),
          :public => boolean(),
          :recoverable => boolean() | nil,
          :runnerId => String.t() | nil,
          :sandboxClass => ExDaytona.Model.SandboxClass.t() | nil,
          :snapshot => String.t() | nil,
          :spot => boolean() | nil,
          :spotEvictedAt => String.t() | nil,
          :state => ExDaytona.Model.SandboxState.t() | nil,
          :target => String.t(),
          :toolboxProxyUrl => String.t(),
          :updatedAt => String.t() | nil,
          :user => String.t(),
          :warmPoolId => String.t() | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:desiredState, :struct, ExDaytona.Model.SandboxDesiredState)
    |> Deserializer.deserialize(:gpuType, :struct, ExDaytona.Model.GpuType)
    |> Deserializer.deserialize(:sandboxClass, :struct, ExDaytona.Model.SandboxClass)
    |> Deserializer.deserialize(:state, :struct, ExDaytona.Model.SandboxState)
  end
end
