# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.SessionExecuteResponse do
  @moduledoc """
  SessionExecuteResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :cmdId,
    :exitCode,
    :output,
    :stderr,
    :stdout
  ]

  @type t :: %__MODULE__{
          :cmdId => String.t(),
          :exitCode => integer() | nil,
          :output => String.t() | nil,
          :stderr => String.t() | nil,
          :stdout => String.t() | nil
        }

  def decode(value) do
    value
  end
end
