# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.Session do
  @moduledoc """
  Session model.
  """

  @derive JSON.Encoder
  defstruct [
    :commands,
    :sessionId
  ]

  @type t :: %__MODULE__{
          :commands => [ExDaytona.Model.Command.t()],
          :sessionId => String.t()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:commands, :list, ExDaytona.Model.Command)
  end
end
