# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.SessionExecuteRequest do
  @moduledoc """
  SessionExecuteRequest model.
  """

  @derive JSON.Encoder
  defstruct [
    :async,
    :command,
    :runAsync,
    :suppressInputEcho
  ]

  @type t :: %__MODULE__{
          :async => boolean() | nil,
          :command => String.t(),
          :runAsync => boolean() | nil,
          :suppressInputEcho => boolean() | nil
        }

  def decode(value) do
    value
  end
end
