# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.SnapshotDto do
  @moduledoc """
  SnapshotDto model.
  """

  # Encode without nil fields: unset optional fields must be OMITTED from
  # request JSON, not sent as explicit nulls — real servers (Daytona
  # included) reject bodies full of nulls that a bare {} would satisfy.
  defimpl JSON.Encoder do
    def encode(struct, encoder) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_field, value} -> is_nil(value) end)
      |> Map.new()
      |> encoder.(encoder)
    end
  end

  defstruct [
    :buildInfo,
    :cpu,
    :createdAt,
    :disk,
    :entrypoint,
    :errorReason,
    :general,
    :gpu,
    :gpuType,
    :id,
    :imageName,
    :initialRunnerId,
    :lastUsedAt,
    :mem,
    :name,
    :organizationId,
    :ref,
    :regionIds,
    :sandboxClass,
    :size,
    :sourceSandboxId,
    :state,
    :updatedAt
  ]

  @type t :: %__MODULE__{
          :buildInfo => ExDaytona.Model.BuildInfo.t() | nil,
          :cpu => number(),
          :createdAt => DateTime.t(),
          :disk => number(),
          :entrypoint => [String.t()] | nil,
          :errorReason => String.t() | nil,
          :general => boolean(),
          :gpu => number(),
          :gpuType => ExDaytona.Model.GpuType.t() | nil,
          :id => String.t(),
          :imageName => String.t() | nil,
          :initialRunnerId => String.t() | nil,
          :lastUsedAt => DateTime.t() | nil,
          :mem => number(),
          :name => String.t(),
          :organizationId => String.t() | nil,
          :ref => String.t() | nil,
          :regionIds => [String.t()] | nil,
          :sandboxClass => String.t() | nil,
          :size => number() | nil,
          :sourceSandboxId => String.t() | nil,
          :state => ExDaytona.Model.SnapshotState.t(),
          :updatedAt => DateTime.t()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:buildInfo, :struct, ExDaytona.Model.BuildInfo)
    |> Deserializer.deserialize(:gpuType, :struct, ExDaytona.Model.GpuType)
    |> Deserializer.deserialize(:state, :struct, ExDaytona.Model.SnapshotState)
  end
end
