# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.SshAccessDto do
  @moduledoc """
  SshAccessDto model.
  """

  @derive JSON.Encoder
  defstruct [
    :createdAt,
    :expiresAt,
    :id,
    :sandboxId,
    :sshCommand,
    :token,
    :updatedAt
  ]

  @type t :: %__MODULE__{
          :createdAt => DateTime.t(),
          :expiresAt => DateTime.t(),
          :id => String.t(),
          :sandboxId => String.t(),
          :sshCommand => String.t(),
          :token => String.t(),
          :updatedAt => DateTime.t()
        }

  def decode(value) do
    value
  end
end
