# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.SsoOidcConfig do
  @moduledoc """
  SsoOidcConfig model.
  """

  @derive JSON.Encoder
  defstruct [
    :clientId,
    :issuer
  ]

  @type t :: %__MODULE__{
          :clientId => String.t(),
          :issuer => String.t()
        }

  def decode(value) do
    value
  end
end
