# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.StorageAccessDto do
  @moduledoc """
  StorageAccessDto model.
  """

  @derive JSON.Encoder
  defstruct [
    :accessKey,
    :bucket,
    :organizationId,
    :region,
    :secret,
    :sessionToken,
    :storageUrl
  ]

  @type t :: %__MODULE__{
          :accessKey => String.t(),
          :bucket => String.t(),
          :organizationId => String.t(),
          :region => String.t(),
          :secret => String.t(),
          :sessionToken => String.t(),
          :storageUrl => String.t()
        }

  def decode(value) do
    value
  end
end
