# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.StringFilter do
  @moduledoc """
  StringFilter model.
  """

  @derive JSON.Encoder
  defstruct [
    :eq,
    :in,
    :not,
    :notIn
  ]

  @type t :: %__MODULE__{
          :eq => String.t() | nil,
          :in => [String.t()] | nil,
          :not => String.t() | nil,
          :notIn => [String.t()] | nil
        }

  def decode(value) do
    value
  end
end
