# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.SystemMetrics do
  @moduledoc """
  SystemMetrics model.
  """

  @derive JSON.Encoder
  defstruct [
    :cpuCount,
    :cpuUsedPct,
    :diskFree,
    :diskTotal,
    :diskUsed,
    :memCache,
    :memTotal,
    :memUsed,
    :timestamp,
    :timestampUnix
  ]

  @type t :: %__MODULE__{
          :cpuCount => integer() | nil,
          :cpuUsedPct => float() | nil,
          :diskFree => integer() | nil,
          :diskTotal => integer() | nil,
          :diskUsed => integer() | nil,
          :memCache => integer() | nil,
          :memTotal => integer() | nil,
          :memUsed => integer() | nil,
          :timestamp => String.t() | nil,
          :timestampUnix => integer() | nil
        }

  def decode(value) do
    value
  end
end
