# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.TestIdentityProviderConnectionResponse do
  @moduledoc """
  TestIdentityProviderConnectionResponse model.
  """

  @derive JSON.Encoder
  defstruct [
    :error,
    :issuer,
    :success
  ]

  @type t :: %__MODULE__{
          :error => String.t() | nil,
          :issuer => String.t() | nil,
          :success => boolean()
        }

  def decode(value) do
    value
  end
end
