# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.TraceSpan do
  @moduledoc """
  TraceSpan model.
  """

  @derive JSON.Encoder
  defstruct [
    :durationNs,
    :parentSpanId,
    :spanAttributes,
    :spanId,
    :spanName,
    :statusCode,
    :statusMessage,
    :timestamp,
    :traceId
  ]

  @type t :: %__MODULE__{
          :durationNs => number(),
          :parentSpanId => String.t() | nil,
          :spanAttributes => %{optional(String.t()) => String.t()},
          :spanId => String.t(),
          :spanName => String.t(),
          :statusCode => String.t() | nil,
          :statusMessage => String.t() | nil,
          :timestamp => String.t(),
          :traceId => String.t()
        }

  def decode(value) do
    value
  end
end
