# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.TraceSummary do
  @moduledoc """
  TraceSummary model.
  """

  @derive JSON.Encoder
  defstruct [
    :durationMs,
    :endTime,
    :rootSpanName,
    :spanCount,
    :startTime,
    :statusCode,
    :traceId
  ]

  @type t :: %__MODULE__{
          :durationMs => number(),
          :endTime => String.t(),
          :rootSpanName => String.t(),
          :spanCount => number(),
          :startTime => String.t(),
          :statusCode => String.t() | nil,
          :traceId => String.t()
        }

  def decode(value) do
    value
  end
end
