# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.UpdateLastActivity do
  @moduledoc """
  UpdateLastActivity model.
  """

  @derive JSON.Encoder
  defstruct [
    :activityType
  ]

  @type t :: %__MODULE__{
          :activityType => String.t() | nil
        }

  def decode(value) do
    value
  end
end
