# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.UpdateJobStatus do
  @moduledoc """
  UpdateJobStatus model.
  """

  @derive JSON.Encoder
  defstruct [
    :errorMessage,
    :resultMetadata,
    :status
  ]

  @type t :: %__MODULE__{
          :errorMessage => String.t() | nil,
          :resultMetadata => String.t() | nil,
          :status => ExDaytona.Model.JobStatus.t()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:status, :struct, ExDaytona.Model.JobStatus)
  end
end
