# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.UpdateWarmPool do
  @moduledoc """
  UpdateWarmPool model.
  """

  @derive JSON.Encoder
  defstruct [
    :pool
  ]

  @type t :: %__MODULE__{
          :pool => number()
        }

  def decode(value) do
    value
  end
end
