# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.UpdateOrganizationRegionQuota do
  @moduledoc """
  UpdateOrganizationRegionQuota model.
  """

  @derive JSON.Encoder
  defstruct [
    :allowedGpuTypes,
    :maxCpuPerGpu,
    :maxCpuPerSandbox,
    :maxDiskPerGpu,
    :maxDiskPerNonEphemeralSandbox,
    :maxDiskPerSandbox,
    :maxMemoryPerGpu,
    :maxMemoryPerSandbox,
    :maxSandboxLifespan,
    :sandboxClass,
    :totalCpuQuota,
    :totalDiskQuota,
    :totalGpuQuota,
    :totalMemoryQuota
  ]

  @type t :: %__MODULE__{
          :allowedGpuTypes => [ExDaytona.Model.GpuType.t()] | nil,
          :maxCpuPerGpu => number() | nil,
          :maxCpuPerSandbox => number() | nil,
          :maxDiskPerGpu => number() | nil,
          :maxDiskPerNonEphemeralSandbox => number() | nil,
          :maxDiskPerSandbox => number() | nil,
          :maxMemoryPerGpu => number() | nil,
          :maxMemoryPerSandbox => number() | nil,
          :maxSandboxLifespan => number() | nil,
          :sandboxClass => ExDaytona.Model.SandboxClass.t() | nil,
          :totalCpuQuota => number() | nil,
          :totalDiskQuota => number() | nil,
          :totalGpuQuota => number() | nil,
          :totalMemoryQuota => number() | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:allowedGpuTypes, :list, ExDaytona.Model.GpuType)
    |> Deserializer.deserialize(:sandboxClass, :struct, ExDaytona.Model.SandboxClass)
  end
end
