# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.UpdateSandboxNetworkSettings do
  @moduledoc """
  UpdateSandboxNetworkSettings model.
  """

  @derive JSON.Encoder
  defstruct [
    :domainAllowList,
    :networkAllowList,
    :networkBlockAll
  ]

  @type t :: %__MODULE__{
          :domainAllowList => String.t() | nil,
          :networkAllowList => String.t() | nil,
          :networkBlockAll => boolean() | nil
        }

  def decode(value) do
    value
  end
end
