# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.UpdateOrganizationQuota do
  @moduledoc """
  UpdateOrganizationQuota model.
  """

  @derive JSON.Encoder
  defstruct [
    :authenticatedRateLimit,
    :authenticatedRateLimitTtlSeconds,
    :maxConcurrentSnapshotProcessing,
    :maxCpuPerSandbox,
    :maxDiskPerSandbox,
    :maxMemoryPerSandbox,
    :maxSecretsPerSandbox,
    :maxSnapshotSize,
    :sandboxCreateRateLimit,
    :sandboxCreateRateLimitTtlSeconds,
    :sandboxLifecycleRateLimit,
    :sandboxLifecycleRateLimitTtlSeconds,
    :secretQuota,
    :snapshotDeactivationTimeoutMinutes,
    :snapshotQuota,
    :volumeQuota
  ]

  @type t :: %__MODULE__{
          :authenticatedRateLimit => number() | nil,
          :authenticatedRateLimitTtlSeconds => number() | nil,
          :maxConcurrentSnapshotProcessing => number() | nil,
          :maxCpuPerSandbox => number() | nil,
          :maxDiskPerSandbox => number() | nil,
          :maxMemoryPerSandbox => number() | nil,
          :maxSecretsPerSandbox => number() | nil,
          :maxSnapshotSize => number() | nil,
          :sandboxCreateRateLimit => number() | nil,
          :sandboxCreateRateLimitTtlSeconds => number() | nil,
          :sandboxLifecycleRateLimit => number() | nil,
          :sandboxLifecycleRateLimitTtlSeconds => number() | nil,
          :secretQuota => number() | nil,
          :snapshotDeactivationTimeoutMinutes => number() | nil,
          :snapshotQuota => number() | nil,
          :volumeQuota => number() | nil
        }

  def decode(value) do
    value
  end
end
