# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.UpdateDockerRegistry do
  @moduledoc """
  UpdateDockerRegistry model.
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :password,
    :project,
    :url,
    :username
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :password => String.t() | nil,
          :project => String.t() | nil,
          :url => String.t(),
          :username => String.t()
        }

  def decode(value) do
    value
  end
end
