# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.UpdateOrganizationMemberAccess do
  @moduledoc """
  UpdateOrganizationMemberAccess model.
  """

  @derive JSON.Encoder
  defstruct [
    :assignedRoleIds,
    :role
  ]

  @type t :: %__MODULE__{
          :assignedRoleIds => [String.t()],
          :role => String.t()
        }

  def decode(value) do
    value
  end
end
