# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.UpdateIdentityProvider do
  @moduledoc """
  UpdateIdentityProvider model.
  """

  # Encode without nil fields: unset optional fields must be OMITTED from
  # request JSON, not sent as explicit nulls — real servers (Daytona
  # included) reject bodies full of nulls that a bare {} would satisfy.
  defimpl JSON.Encoder do
    def encode(struct, encoder) do
      struct
      |> Map.from_struct()
      |> Enum.reject(fn {_field, value} -> is_nil(value) end)
      |> Map.new()
      |> encoder.(encoder)
    end
  end

  defstruct [
    :allowAnyDomain,
    :defaultAssignedRoleIds,
    :emailDomains,
    :enabled,
    :name,
    :oidcConfig,
    :trustEmailVerified
  ]

  @type t :: %__MODULE__{
          :allowAnyDomain => boolean() | nil,
          :defaultAssignedRoleIds => [String.t()] | nil,
          :emailDomains => [String.t()] | nil,
          :enabled => boolean() | nil,
          :name => String.t() | nil,
          :oidcConfig => ExDaytona.Model.UpdateOidcIdPConfig.t() | nil,
          :trustEmailVerified => boolean() | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:oidcConfig, :struct, ExDaytona.Model.UpdateOidcIdPConfig)
  end
end
