# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.User do
  @moduledoc """
  User model.
  """

  @derive JSON.Encoder
  defstruct [
    :createdAt,
    :email,
    :emailVerified,
    :id,
    :name,
    :publicKeys,
    :pylonEmailHash
  ]

  @type t :: %__MODULE__{
          :createdAt => DateTime.t(),
          :email => String.t(),
          :emailVerified => boolean(),
          :id => String.t(),
          :name => String.t(),
          :publicKeys => [ExDaytona.Model.UserPublicKey.t()],
          :pylonEmailHash => String.t() | nil
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:publicKeys, :list, ExDaytona.Model.UserPublicKey)
  end
end
