# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.VolumeDto do
  @moduledoc """
  VolumeDto model.
  """

  @derive JSON.Encoder
  defstruct [
    :createdAt,
    :errorReason,
    :id,
    :lastUsedAt,
    :name,
    :organizationId,
    :state,
    :updatedAt
  ]

  @type t :: %__MODULE__{
          :createdAt => String.t(),
          :errorReason => String.t() | nil,
          :id => String.t(),
          :lastUsedAt => String.t() | nil,
          :name => String.t(),
          :organizationId => String.t(),
          :state => ExDaytona.Model.VolumeState.t(),
          :updatedAt => String.t()
        }

  alias ExDaytona.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:state, :struct, ExDaytona.Model.VolumeState)
  end
end
