# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.WebhookEvent do
  @moduledoc """
  The type of event being sent
  """

  @typedoc """
  Enum values are plain strings on the wire and stay strings at runtime.
  """
  @type t :: String.t()

  def decode(value) do
    value
  end
end
