# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Model.WebhookInitializationStatus do
  @moduledoc """
  WebhookInitializationStatus model.
  """

  @derive JSON.Encoder
  defstruct [
    :createdAt,
    :lastError,
    :organizationId,
    :retryCount,
    :svixApplicationId,
    :updatedAt
  ]

  @type t :: %__MODULE__{
          :createdAt => String.t(),
          :lastError => String.t() | nil,
          :organizationId => String.t(),
          :retryCount => number(),
          :svixApplicationId => String.t() | nil,
          :updatedAt => String.t()
        }

  def decode(value) do
    value
  end
end
