# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.Admin do
  @moduledoc """
  API calls for all endpoints tagged `Admin`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Check if an image can be cleaned up

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `image_name` (String.t): Image name with tag to check
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, boolean()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_can_cleanup_image(Tesla.Env.client(), String.t(), keyword()) :: {:ok, boolean()} | {:error, Tesla.Env.t()}
  def admin_can_cleanup_image(connection, image_name, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/admin/snapshots/can-cleanup-image")
      |> add_param(:query, :imageName, image_name)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Create organization for user

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `admin_create_organization` (AdminCreateOrganization): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.Organization.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_create_organization(Tesla.Env.client(), ExDaytona.Model.AdminCreateOrganization.t(), keyword()) ::
          {:ok, ExDaytona.Model.Organization.t()} | {:error, Tesla.Env.t()}
  def admin_create_organization(connection, admin_create_organization, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/admin/organizations")
      |> add_param(:body, :body, admin_create_organization)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, ExDaytona.Model.Organization}
    ])
  end

  @doc """
  Create organization region quota

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): Organization ID
  - `region_id` (String.t): ID of the region the new quota applies to
  - `create_organization_region_quota` (CreateOrganizationRegionQuota): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.RegionQuota.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_create_organization_region_quota(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          ExDaytona.Model.CreateOrganizationRegionQuota.t(),
          keyword()
        ) :: {:ok, ExDaytona.Model.RegionQuota.t()} | {:error, Tesla.Env.t()}
  def admin_create_organization_region_quota(
        connection,
        organization_id,
        region_id,
        create_organization_region_quota,
        _opts \\ []
      ) do
    request =
      %{}
      |> method(:post)
      |> url("/admin/organizations/#{organization_id}/quota/#{region_id}")
      |> add_param(:body, :body, create_organization_region_quota)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, ExDaytona.Model.RegionQuota}
    ])
  end

  @doc """
  Create runner

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `admin_create_runner` (AdminCreateRunner): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.CreateRunnerResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_create_runner(Tesla.Env.client(), ExDaytona.Model.AdminCreateRunner.t(), keyword()) ::
          {:ok, ExDaytona.Model.CreateRunnerResponse.t()} | {:error, Tesla.Env.t()}
  def admin_create_runner(connection, admin_create_runner, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/admin/runners")
      |> add_param(:body, :body, admin_create_runner)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, ExDaytona.Model.CreateRunnerResponse}
    ])
  end

  @doc """
  Create user

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `create_user` (CreateUser): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_create_user(Tesla.Env.client(), ExDaytona.Model.CreateUser.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def admin_create_user(connection, create_user, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/admin/users")
      |> add_param(:body, :body, create_user)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, false}
    ])
  end

  @doc """
  Delete organization region quota

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): Organization ID
  - `region_id` (String.t): Region ID
  - `sandbox_class` (SandboxClass): Sandbox class
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_delete_organization_region_quota(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          ExDaytona.Model.SandboxClass.t(),
          keyword()
        ) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def admin_delete_organization_region_quota(connection, organization_id, region_id, sandbox_class, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/admin/organizations/#{organization_id}/quota/#{region_id}/#{sandbox_class}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false}
    ])
  end

  @doc """
  Delete runner

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Runner ID
  - `opts` (keyword): Optional parameters
    - `:force` (boolean()): Delete the runner without waiting for sandboxes already marked for destruction. Requires the runner to have stopped reporting as ready.

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_delete_runner(Tesla.Env.client(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def admin_delete_runner(connection, id, opts \\ []) do
    optional_params = %{
      :force => :query
    }

    request =
      %{}
      |> method(:delete)
      |> url("/admin/runners/#{id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false}
    ])
  end

  @doc """
  Get all audit logs

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (number()): Page number of the results
    - `:limit` (number()): Number of results per page
    - `:from` (DateTime.t): Deprecated alias for `createdAt[gte]`. From date (ISO 8601 format).
    - `:to` (DateTime.t): Deprecated alias for `createdAt[lte]`. To date (ISO 8601 format).
    - `:nextToken` (String.t): Token for cursor-based pagination. When provided, takes precedence over page parameter.
    - `:id` (StringFilter): Filter by audit log ID.
    - `:actorId` (StringFilter): Filter by actor user ID.
    - `:actorEmail` (StringFilter): Filter by actor email.
    - `:actorApiKeyPrefix` (StringFilter): Filter by actor API key prefix.
    - `:actorApiKeySuffix` (StringFilter): Filter by actor API key suffix.
    - `:action` (StringFilter): Filter by action.
    - `:targetType` (StringFilter): Filter by target type.
    - `:targetId` (StringFilter): Filter by target ID.
    - `:statusCode` (IntFilter): Filter by HTTP status code.
    - `:createdAt` (DateFilter): Filter by creation timestamp.

  ### Returns

  - `{:ok, ExDaytona.Model.PaginatedAuditLogs.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_get_all_audit_logs(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.PaginatedAuditLogs.t()} | {:error, Tesla.Env.t()}
  def admin_get_all_audit_logs(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :limit => :query,
      :from => :query,
      :to => :query,
      :nextToken => :query,
      :id => :query,
      :actorId => :query,
      :actorEmail => :query,
      :actorApiKeyPrefix => :query,
      :actorApiKeySuffix => :query,
      :action => :query,
      :targetType => :query,
      :targetId => :query,
      :statusCode => :query,
      :createdAt => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/admin/audit")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.PaginatedAuditLogs}
    ])
  end

  @doc """
  Get delivery attempts for a webhook message

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): 
  - `message_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%map(){}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_get_message_attempts(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, [map()]} | {:error, Tesla.Env.t()}
  def admin_get_message_attempts(connection, organization_id, message_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/admin/webhooks/organizations/#{organization_id}/messages/#{message_id}/attempts")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, []}
    ])
  end

  @doc """
  Get organization region quota

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): Organization ID
  - `region_id` (String.t): Region ID
  - `sandbox_class` (SandboxClass): Sandbox class
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.RegionQuota.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_get_organization_region_quota(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          ExDaytona.Model.SandboxClass.t(),
          keyword()
        ) :: {:ok, ExDaytona.Model.RegionQuota.t()} | {:error, Tesla.Env.t()}
  def admin_get_organization_region_quota(connection, organization_id, region_id, sandbox_class, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/admin/organizations/#{organization_id}/quota/#{region_id}/#{sandbox_class}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.RegionQuota}
    ])
  end

  @doc """
  Get runner by ID

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Runner ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.RunnerFull.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_get_runner_by_id(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.RunnerFull.t()} | {:error, Tesla.Env.t()}
  def admin_get_runner_by_id(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/admin/runners/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.RunnerFull}
    ])
  end

  @doc """
  Get user by ID

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.User.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_get_user(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.User.t()} | {:error, Tesla.Env.t()}
  def admin_get_user(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/admin/users/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.User}
    ])
  end

  @doc """
  Get webhook service status

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.AdminGetWebhookStatus200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_get_webhook_status(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.AdminGetWebhookStatus200Response.t()} | {:error, Tesla.Env.t()}
  def admin_get_webhook_status(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/admin/webhooks/status")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.AdminGetWebhookStatus200Response}
    ])
  end

  @doc """
  Initialize webhooks for an organization

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_initialize_webhooks(Tesla.Env.client(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def admin_initialize_webhooks(connection, organization_id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/admin/webhooks/organizations/#{organization_id}/initialize")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, false},
      {404, false}
    ])
  end

  @doc """
  List all runners

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:regionId` (String.t): Filter runners by region ID

  ### Returns

  - `{:ok, [%RunnerFull{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_list_runners(Tesla.Env.client(), keyword()) ::
          {:ok, [ExDaytona.Model.RunnerFull.t()]} | {:error, Tesla.Env.t()}
  def admin_list_runners(connection, opts \\ []) do
    optional_params = %{
      :regionId => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/admin/runners")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.RunnerFull}
    ])
  end

  @doc """
  List all users

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_list_users(Tesla.Env.client(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def admin_list_users(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/admin/users")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Recover sandbox from error state as an admin

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): ID of the sandbox
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_recover_sandbox(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def admin_recover_sandbox(connection, sandbox_id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/admin/sandbox/#{sandbox_id}/recover")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Regenerate user key pair

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_regenerate_key_pair(Tesla.Env.client(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def admin_regenerate_key_pair(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/admin/users/#{id}/regenerate-key-pair")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, false}
    ])
  end

  @doc """
  Send a webhook message to an organization

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): 
  - `send_webhook_dto` (SendWebhookDto): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_send_webhook(Tesla.Env.client(), String.t(), ExDaytona.Model.SendWebhookDto.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def admin_send_webhook(connection, organization_id, send_webhook_dto, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/admin/webhooks/organizations/#{organization_id}/send")
      |> add_param(:body, :body, send_webhook_dto)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Set default registry

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): ID of the docker registry
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.DockerRegistry.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_set_default_registry(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.DockerRegistry.t()} | {:error, Tesla.Env.t()}
  def admin_set_default_registry(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/admin/docker-registry/#{id}/set-default")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.DockerRegistry}
    ])
  end

  @doc """
  Set snapshot general status

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Snapshot ID
  - `set_snapshot_general_status_dto` (SetSnapshotGeneralStatusDto): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.SnapshotDto.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_set_snapshot_general_status(
          Tesla.Env.client(),
          String.t(),
          ExDaytona.Model.SetSnapshotGeneralStatusDto.t(),
          keyword()
        ) :: {:ok, ExDaytona.Model.SnapshotDto.t()} | {:error, Tesla.Env.t()}
  def admin_set_snapshot_general_status(connection, id, set_snapshot_general_status_dto, _opts \\ []) do
    request =
      %{}
      |> method(:patch)
      |> url("/admin/snapshots/#{id}/general")
      |> add_param(:body, :body, set_snapshot_general_status_dto)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.SnapshotDto}
    ])
  end

  @doc """
  Update organization preview warning

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): Organization ID
  - `organization_preview_warning` (OrganizationPreviewWarning): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_update_organization_preview_warning(
          Tesla.Env.client(),
          String.t(),
          ExDaytona.Model.OrganizationPreviewWarning.t(),
          keyword()
        ) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def admin_update_organization_preview_warning(connection, organization_id, organization_preview_warning, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/admin/organizations/#{organization_id}/preview-warning")
      |> add_param(:body, :body, organization_preview_warning)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false}
    ])
  end

  @doc """
  Update organization region quota

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): Organization ID
  - `region_id` (String.t): Region ID
  - `update_organization_region_quota` (UpdateOrganizationRegionQuota): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_update_organization_region_quota(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          ExDaytona.Model.UpdateOrganizationRegionQuota.t(),
          keyword()
        ) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def admin_update_organization_region_quota(
        connection,
        organization_id,
        region_id,
        update_organization_region_quota,
        _opts \\ []
      ) do
    request =
      %{}
      |> method(:patch)
      |> url("/admin/organizations/#{organization_id}/quota/#{region_id}")
      |> add_param(:body, :body, update_organization_region_quota)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false}
    ])
  end

  @doc """
  Update runner scheduling status

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec admin_update_runner_scheduling(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def admin_update_runner_scheduling(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:patch)
      |> url("/admin/runners/#{id}/scheduling")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false}
    ])
  end
end
