# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.ApiKeys do
  @moduledoc """
  API calls for all endpoints tagged `ApiKeys`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Create API key

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `create_api_key` (CreateApiKey): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.ApiKeyResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_api_key(Tesla.Env.client(), ExDaytona.Model.CreateApiKey.t(), keyword()) ::
          {:ok, ExDaytona.Model.ApiKeyResponse.t()} | {:error, Tesla.Env.t()}
  def create_api_key(connection, create_api_key, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/api-keys")
      |> add_param(:body, :body, create_api_key)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, ExDaytona.Model.ApiKeyResponse}
    ])
  end

  @doc """
  Delete API key

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `name` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_api_key(Tesla.Env.client(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def delete_api_key(connection, name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:delete)
      |> url("/api-keys/#{name}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false}
    ])
  end

  @doc """
  Delete API key for user

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `user_id` (String.t): 
  - `name` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_api_key_for_user(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def delete_api_key_for_user(connection, user_id, name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:delete)
      |> url("/api-keys/#{user_id}/#{name}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false}
    ])
  end

  @doc """
  Get API key

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `name` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.ApiKeyList.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_api_key(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.ApiKeyList.t()} | {:error, Tesla.Env.t()}
  def get_api_key(connection, name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/api-keys/#{name}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ApiKeyList}
    ])
  end

  @doc """
  Get current API key's details

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.ApiKeyList.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_current_api_key(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.ApiKeyList.t()} | {:error, Tesla.Env.t()}
  def get_current_api_key(connection, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/api-keys/current")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ApiKeyList}
    ])
  end

  @doc """
  List API keys

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, [%ApiKeyList{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_api_keys(Tesla.Env.client(), keyword()) ::
          {:ok, nil} | {:ok, [ExDaytona.Model.ApiKeyList.t()]} | {:error, Tesla.Env.t()}
  def list_api_keys(connection, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/api-keys")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ApiKeyList},
      {500, false}
    ])
  end
end
