# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.ComputerUse do
  @moduledoc """
  API calls for all endpoints tagged `ComputerUse`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Click mouse button
  Click the mouse button at the specified coordinates

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `mouse_click_request` (MouseClickRequest): Mouse click request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.MouseClickResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec click(Tesla.Env.client(), ExDaytona.Model.MouseClickRequest.t(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, ExDaytona.Model.MouseClickResponse.t()}
          | {:error, Tesla.Env.t()}
  def click(connection, mouse_click_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/computeruse/mouse/click")
      |> add_param(:body, :body, mouse_click_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.MouseClickResponse},
      {400, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Delete a recording
  Delete a recording file by ID

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Recording ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_recording(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, nil} | {:ok, ExDaytona.Model.ErrorResponse.t()} | {:error, Tesla.Env.t()}
  def delete_recording(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/computeruse/recordings/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {400, ExDaytona.Model.ErrorResponse},
      {404, ExDaytona.Model.ErrorResponse},
      {409, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Download a recording
  Download a recording by providing its ID

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Recording ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec download_recording(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()} | {:ok, String.t()} | {:error, Tesla.Env.t()}
  def download_recording(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/computeruse/recordings/#{id}/download")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {400, ExDaytona.Model.ErrorResponse},
      {404, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Drag mouse
  Drag the mouse from start to end coordinates

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `mouse_drag_request` (MouseDragRequest): Mouse drag request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.MouseDragResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec drag(Tesla.Env.client(), ExDaytona.Model.MouseDragRequest.t(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, ExDaytona.Model.MouseDragResponse.t()}
          | {:error, Tesla.Env.t()}
  def drag(connection, mouse_drag_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/computeruse/mouse/drag")
      |> add_param(:body, :body, mouse_drag_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.MouseDragResponse},
      {400, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Find accessibility nodes
  Search the AT-SPI tree for nodes matching a role/name/state filter and return a flat list.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `find_accessibility_nodes_request` (FindAccessibilityNodesRequest): Find request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.AccessibilityNodesResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec find_accessibility_nodes(Tesla.Env.client(), ExDaytona.Model.FindAccessibilityNodesRequest.t(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, ExDaytona.Model.AccessibilityNodesResponse.t()}
          | {:error, Tesla.Env.t()}
  def find_accessibility_nodes(connection, find_accessibility_nodes_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/computeruse/a11y/find")
      |> add_param(:body, :body, find_accessibility_nodes_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.AccessibilityNodesResponse},
      {400, ExDaytona.Model.ErrorResponse},
      {404, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse},
      {503, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Focus an accessibility node
  Move keyboard focus to the AT-SPI node identified by id (bus-name:object-path).

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `accessibility_node_request` (AccessibilityNodeRequest): Node focus request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, map()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec focus_accessibility_node(Tesla.Env.client(), ExDaytona.Model.AccessibilityNodeRequest.t(), keyword()) ::
          {:ok, map()} | {:ok, ExDaytona.Model.ErrorResponse.t()} | {:error, Tesla.Env.t()}
  def focus_accessibility_node(connection, accessibility_node_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/computeruse/a11y/node/focus")
      |> add_param(:body, :body, accessibility_node_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}},
      {400, ExDaytona.Model.ErrorResponse},
      {404, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse},
      {503, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Get accessibility tree
  Fetch the AT-SPI accessibility tree for the focused application, a specific PID, or all registered applications.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:scope` (String.t): Scope: focused | pid | all (default: focused)
    - `:pid` (integer()): Process ID when scope=pid
    - `:maxDepth` (integer()): Max tree depth (-1 unbounded, 0 root only; default -1)

  ### Returns

  - `{:ok, ExDaytona.Model.AccessibilityTreeResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_accessibility_tree(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, ExDaytona.Model.AccessibilityTreeResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_accessibility_tree(connection, opts \\ []) do
    optional_params = %{
      :scope => :query,
      :pid => :query,
      :maxDepth => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/computeruse/a11y/tree")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.AccessibilityTreeResponse},
      {400, ExDaytona.Model.ErrorResponse},
      {404, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse},
      {503, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Get computer use process status
  Get the status of all computer use processes

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.ComputerUseStatusResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_computer_use_status(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.ComputerUseStatusResponse.t()} | {:error, Tesla.Env.t()}
  def get_computer_use_status(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/computeruse/process-status")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ComputerUseStatusResponse}
    ])
  end

  @doc """
  Get computer use status
  Get the current status of the computer use system

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.ComputerUseStatusResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_computer_use_system_status(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, ExDaytona.Model.ComputerUseStatusResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_computer_use_system_status(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/computeruse/status")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ComputerUseStatusResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Get display information
  Get information about all available displays

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.DisplayInfoResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_display_info(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, ExDaytona.Model.DisplayInfoResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_display_info(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/computeruse/display/info")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.DisplayInfoResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Get mouse position
  Get the current mouse cursor position

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.MousePositionResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_mouse_position(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, ExDaytona.Model.MousePositionResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_mouse_position(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/computeruse/mouse/position")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.MousePositionResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Get process errors
  Get errors for a specific computer use process

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `process_name` (String.t): Process name to get errors for
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.ProcessErrorsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_process_errors(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.ProcessErrorsResponse.t()} | {:error, Tesla.Env.t()}
  def get_process_errors(connection, process_name, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/computeruse/process/#{process_name}/errors")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ProcessErrorsResponse}
    ])
  end

  @doc """
  Get process logs
  Get logs for a specific computer use process

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `process_name` (String.t): Process name to get logs for
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.ProcessLogsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_process_logs(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.ProcessLogsResponse.t()} | {:error, Tesla.Env.t()}
  def get_process_logs(connection, process_name, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/computeruse/process/#{process_name}/logs")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ProcessLogsResponse}
    ])
  end

  @doc """
  Get specific process status
  Check if a specific computer use process is running

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `process_name` (String.t): Process name to check
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.ProcessStatusResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_process_status(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.ProcessStatusResponse.t()} | {:error, Tesla.Env.t()}
  def get_process_status(connection, process_name, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/computeruse/process/#{process_name}/status")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ProcessStatusResponse}
    ])
  end

  @doc """
  Get recording details
  Get details of a specific recording by ID

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Recording ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.Recording.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_recording(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Recording.t()} | {:ok, ExDaytona.Model.ErrorResponse.t()} | {:error, Tesla.Env.t()}
  def get_recording(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/computeruse/recordings/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Recording},
      {400, ExDaytona.Model.ErrorResponse},
      {404, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Get windows information
  Get information about all open windows

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.WindowsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_windows(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, ExDaytona.Model.WindowsResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_windows(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/computeruse/display/windows")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.WindowsResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Invoke an action on an accessibility node
  Call an AT-SPI Action on the node. Leave action empty to invoke the node's primary (first) action.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `accessibility_invoke_request` (AccessibilityInvokeRequest): Invoke request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, map()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec invoke_accessibility_node(Tesla.Env.client(), ExDaytona.Model.AccessibilityInvokeRequest.t(), keyword()) ::
          {:ok, map()} | {:ok, ExDaytona.Model.ErrorResponse.t()} | {:error, Tesla.Env.t()}
  def invoke_accessibility_node(connection, accessibility_invoke_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/computeruse/a11y/node/invoke")
      |> add_param(:body, :body, accessibility_invoke_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}},
      {400, ExDaytona.Model.ErrorResponse},
      {404, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse},
      {503, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  List all recordings
  Get a list of all recordings (active and completed)

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.ListRecordingsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_recordings(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, ExDaytona.Model.ListRecordingsResponse.t()}
          | {:error, Tesla.Env.t()}
  def list_recordings(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/computeruse/recordings")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ListRecordingsResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Move mouse cursor
  Move the mouse cursor to the specified coordinates

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `mouse_move_request` (MouseMoveRequest): Mouse move request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.MousePositionResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec move_mouse(Tesla.Env.client(), ExDaytona.Model.MouseMoveRequest.t(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, ExDaytona.Model.MousePositionResponse.t()}
          | {:error, Tesla.Env.t()}
  def move_mouse(connection, mouse_move_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/computeruse/mouse/move")
      |> add_param(:body, :body, mouse_move_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.MousePositionResponse},
      {400, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Press hotkey
  Press a hotkey combination (e.g., ctrl+c, cmd+v)

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `keyboard_hotkey_request` (KeyboardHotkeyRequest): Hotkey press request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, map()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec press_hotkey(Tesla.Env.client(), ExDaytona.Model.KeyboardHotkeyRequest.t(), keyword()) ::
          {:ok, map()} | {:ok, ExDaytona.Model.ErrorResponse.t()} | {:error, Tesla.Env.t()}
  def press_hotkey(connection, keyboard_hotkey_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/computeruse/keyboard/hotkey")
      |> add_param(:body, :body, keyboard_hotkey_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}},
      {400, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Press key
  Press a key with optional modifiers

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `keyboard_press_request` (KeyboardPressRequest): Key press request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, map()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec press_key(Tesla.Env.client(), ExDaytona.Model.KeyboardPressRequest.t(), keyword()) ::
          {:ok, map()} | {:ok, ExDaytona.Model.ErrorResponse.t()} | {:error, Tesla.Env.t()}
  def press_key(connection, keyboard_press_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/computeruse/keyboard/key")
      |> add_param(:body, :body, keyboard_press_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}},
      {400, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Restart specific process
  Restart a specific computer use process

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `process_name` (String.t): Process name to restart
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.ProcessRestartResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec restart_process(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.ProcessRestartResponse.t()} | {:error, Tesla.Env.t()}
  def restart_process(connection, process_name, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/computeruse/process/#{process_name}/restart")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ProcessRestartResponse}
    ])
  end

  @doc """
  Scroll mouse wheel
  Scroll the mouse wheel at the specified coordinates

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `mouse_scroll_request` (MouseScrollRequest): Mouse scroll request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.ScrollResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec scroll(Tesla.Env.client(), ExDaytona.Model.MouseScrollRequest.t(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()} | {:ok, ExDaytona.Model.ScrollResponse.t()} | {:error, Tesla.Env.t()}
  def scroll(connection, mouse_scroll_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/computeruse/mouse/scroll")
      |> add_param(:body, :body, mouse_scroll_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ScrollResponse},
      {400, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Set the value of an accessibility node
  Write the given value to the node via EditableText.SetTextContents or, for numeric controls, Value.CurrentValue.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `accessibility_set_value_request` (AccessibilitySetValueRequest): Set value request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, map()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec set_accessibility_node_value(Tesla.Env.client(), ExDaytona.Model.AccessibilitySetValueRequest.t(), keyword()) ::
          {:ok, map()} | {:ok, ExDaytona.Model.ErrorResponse.t()} | {:error, Tesla.Env.t()}
  def set_accessibility_node_value(connection, accessibility_set_value_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/computeruse/a11y/node/value")
      |> add_param(:body, :body, accessibility_set_value_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}},
      {400, ExDaytona.Model.ErrorResponse},
      {404, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse},
      {503, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Start computer use processes
  Start all computer use processes and return their status

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.ComputerUseStartResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec start_computer_use(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.ComputerUseStartResponse.t()} | {:error, Tesla.Env.t()}
  def start_computer_use(connection, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/computeruse/start")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ComputerUseStartResponse}
    ])
  end

  @doc """
  Start a new recording
  Start a new screen recording session

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (StartRecordingRequest): Recording options

  ### Returns

  - `{:ok, ExDaytona.Model.Recording.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec start_recording(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.Recording.t()} | {:ok, ExDaytona.Model.ErrorResponse.t()} | {:error, Tesla.Env.t()}
  def start_recording(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/computeruse/recordings/start")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, ExDaytona.Model.Recording},
      {400, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse},
      {503, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Stop computer use processes
  Stop all computer use processes and return their status

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.ComputerUseStopResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec stop_computer_use(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.ComputerUseStopResponse.t()} | {:error, Tesla.Env.t()}
  def stop_computer_use(connection, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/computeruse/stop")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ComputerUseStopResponse}
    ])
  end

  @doc """
  Stop a recording
  Stop an active screen recording session

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `stop_recording_request` (StopRecordingRequest): Recording ID to stop
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.Recording.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec stop_recording(Tesla.Env.client(), ExDaytona.Model.StopRecordingRequest.t(), keyword()) ::
          {:ok, ExDaytona.Model.Recording.t()} | {:ok, ExDaytona.Model.ErrorResponse.t()} | {:error, Tesla.Env.t()}
  def stop_recording(connection, stop_recording_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/computeruse/recordings/stop")
      |> add_param(:body, :body, stop_recording_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Recording},
      {400, ExDaytona.Model.ErrorResponse},
      {404, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Take a compressed region screenshot
  Take a compressed screenshot of a specific region of the screen

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `x` (integer()): X coordinate of the region
  - `y` (integer()): Y coordinate of the region
  - `width` (integer()): Width of the region
  - `height` (integer()): Height of the region
  - `opts` (keyword): Optional parameters
    - `:showCursor` (boolean()): Whether to show cursor in screenshot
    - `:format` (String.t): Image format (png or jpeg)
    - `:quality` (integer()): JPEG quality (1-100)
    - `:scale` (number()): Scale factor (0.1-1.0)

  ### Returns

  - `{:ok, ExDaytona.Model.ScreenshotResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec take_compressed_region_screenshot(Tesla.Env.client(), integer(), integer(), integer(), integer(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, ExDaytona.Model.ScreenshotResponse.t()}
          | {:error, Tesla.Env.t()}
  def take_compressed_region_screenshot(connection, x, y, width, height, opts \\ []) do
    optional_params = %{
      :showCursor => :query,
      :format => :query,
      :quality => :query,
      :scale => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/computeruse/screenshot/region/compressed")
      |> add_param(:query, :x, x)
      |> add_param(:query, :y, y)
      |> add_param(:query, :width, width)
      |> add_param(:query, :height, height)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ScreenshotResponse},
      {400, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Take a compressed screenshot
  Take a compressed screenshot of the entire screen

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:showCursor` (boolean()): Whether to show cursor in screenshot
    - `:format` (String.t): Image format (png or jpeg)
    - `:quality` (integer()): JPEG quality (1-100)
    - `:scale` (number()): Scale factor (0.1-1.0)

  ### Returns

  - `{:ok, ExDaytona.Model.ScreenshotResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec take_compressed_screenshot(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, ExDaytona.Model.ScreenshotResponse.t()}
          | {:error, Tesla.Env.t()}
  def take_compressed_screenshot(connection, opts \\ []) do
    optional_params = %{
      :showCursor => :query,
      :format => :query,
      :quality => :query,
      :scale => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/computeruse/screenshot/compressed")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ScreenshotResponse},
      {400, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Take a region screenshot
  Take a screenshot of a specific region of the screen

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `x` (integer()): X coordinate of the region
  - `y` (integer()): Y coordinate of the region
  - `width` (integer()): Width of the region
  - `height` (integer()): Height of the region
  - `opts` (keyword): Optional parameters
    - `:showCursor` (boolean()): Whether to show cursor in screenshot

  ### Returns

  - `{:ok, ExDaytona.Model.ScreenshotResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec take_region_screenshot(Tesla.Env.client(), integer(), integer(), integer(), integer(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, ExDaytona.Model.ScreenshotResponse.t()}
          | {:error, Tesla.Env.t()}
  def take_region_screenshot(connection, x, y, width, height, opts \\ []) do
    optional_params = %{
      :showCursor => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/computeruse/screenshot/region")
      |> add_param(:query, :x, x)
      |> add_param(:query, :y, y)
      |> add_param(:query, :width, width)
      |> add_param(:query, :height, height)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ScreenshotResponse},
      {400, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Take a screenshot
  Take a screenshot of the entire screen

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:showCursor` (boolean()): Whether to show cursor in screenshot

  ### Returns

  - `{:ok, ExDaytona.Model.ScreenshotResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec take_screenshot(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, ExDaytona.Model.ScreenshotResponse.t()}
          | {:error, Tesla.Env.t()}
  def take_screenshot(connection, opts \\ []) do
    optional_params = %{
      :showCursor => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/computeruse/screenshot")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ScreenshotResponse},
      {400, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Type text
  Type text with optional delay between keystrokes

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `keyboard_type_request` (KeyboardTypeRequest): Text typing request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, map()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec type_text(Tesla.Env.client(), ExDaytona.Model.KeyboardTypeRequest.t(), keyword()) ::
          {:ok, map()} | {:ok, ExDaytona.Model.ErrorResponse.t()} | {:error, Tesla.Env.t()}
  def type_text(connection, keyboard_type_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/computeruse/keyboard/type")
      |> add_param(:body, :body, keyboard_type_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}},
      {400, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end
end
