# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.Config do
  @moduledoc """
  API calls for all endpoints tagged `Config`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Get config

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.DaytonaConfiguration.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_config(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.DaytonaConfiguration.t()} | {:error, Tesla.Env.t()}
  def get_config(connection, opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/config")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, ExDaytona.Model.DaytonaConfiguration}
      ],
      opts
    )
  end
end
