# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.DockerRegistry do
  @moduledoc """
  API calls for all endpoints tagged `DockerRegistry`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Create registry

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `create_docker_registry` (CreateDockerRegistry): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.DockerRegistry.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_registry(Tesla.Env.client(), ExDaytona.Model.CreateDockerRegistry.t(), keyword()) ::
          {:ok, ExDaytona.Model.DockerRegistry.t()} | {:error, Tesla.Env.t()}
  def create_registry(connection, create_docker_registry, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/docker-registry")
      |> add_param(:body, :body, create_docker_registry)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {201, ExDaytona.Model.DockerRegistry}
      ],
      opts
    )
  end

  @doc """
  Delete registry

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): ID of the docker registry
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_registry(Tesla.Env.client(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def delete_registry(connection, id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:delete)
      |> url("/docker-registry/#{id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {204, false}
      ],
      opts
    )
  end

  @doc """
  Get registry

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): ID of the docker registry
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.DockerRegistry.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_registry(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.DockerRegistry.t()} | {:error, Tesla.Env.t()}
  def get_registry(connection, id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/docker-registry/#{id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, ExDaytona.Model.DockerRegistry}
      ],
      opts
    )
  end

  @doc """
  Get temporary registry access for pushing snapshots

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:regionId` (String.t): ID of the region where the snapshot will be available (defaults to organization default region)

  ### Returns

  - `{:ok, ExDaytona.Model.RegistryPushAccessDto.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_transient_push_access(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.RegistryPushAccessDto.t()} | {:error, Tesla.Env.t()}
  def get_transient_push_access(connection, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :regionId => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/docker-registry/registry-push-access")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, ExDaytona.Model.RegistryPushAccessDto}
      ],
      opts
    )
  end

  @doc """
  List registries

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, [%DockerRegistry{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_registries(Tesla.Env.client(), keyword()) ::
          {:ok, [ExDaytona.Model.DockerRegistry.t()]} | {:error, Tesla.Env.t()}
  def list_registries(connection, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/docker-registry")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, ExDaytona.Model.DockerRegistry}
      ],
      opts
    )
  end

  @doc """
  Update registry

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): ID of the docker registry
  - `update_docker_registry` (UpdateDockerRegistry): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.DockerRegistry.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_registry(Tesla.Env.client(), String.t(), ExDaytona.Model.UpdateDockerRegistry.t(), keyword()) ::
          {:ok, ExDaytona.Model.DockerRegistry.t()} | {:error, Tesla.Env.t()}
  def update_registry(connection, id, update_docker_registry, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:patch)
      |> url("/docker-registry/#{id}")
      |> add_param(:body, :body, update_docker_registry)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, ExDaytona.Model.DockerRegistry}
      ],
      opts
    )
  end
end
