# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.Git do
  @moduledoc """
  API calls for all endpoints tagged `Git`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Add files to Git staging
  Add files to the Git staging area

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `git_add_request` (GitAddRequest): Add files request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec add_files(Tesla.Env.client(), ExDaytona.Model.GitAddRequest.t(), keyword()) ::
          {:ok, nil} | {:ok, ExDaytona.Model.ErrorResponse.t()} | {:error, Tesla.Env.t()}
  def add_files(connection, git_add_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/git/add")
      |> add_param(:body, :body, git_add_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {400, ExDaytona.Model.ErrorResponse},
      {409, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Add a remote
  Add (or overwrite) a remote in the Git repository

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `git_add_remote_request` (GitAddRemoteRequest): Add remote request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec add_remote(Tesla.Env.client(), ExDaytona.Model.GitAddRemoteRequest.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def add_remote(connection, git_add_remote_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/git/remotes")
      |> add_param(:body, :body, git_add_remote_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, false}
    ])
  end

  @doc """
  Authenticate Git
  Persist Git credentials globally via the credential store. Stores the password in plaintext on disk.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `git_authenticate_request` (GitAuthenticateRequest): Authenticate request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec authenticate(Tesla.Env.client(), ExDaytona.Model.GitAuthenticateRequest.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def authenticate(connection, git_authenticate_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/git/credentials")
      |> add_param(:body, :body, git_authenticate_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Checkout branch or commit
  Switch to a different branch or commit in the Git repository

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `git_checkout_request` (GitCheckoutRequest): Checkout request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec checkout_branch(Tesla.Env.client(), ExDaytona.Model.GitCheckoutRequest.t(), keyword()) ::
          {:ok, nil} | {:ok, ExDaytona.Model.ErrorResponse.t()} | {:error, Tesla.Env.t()}
  def checkout_branch(connection, git_checkout_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/git/checkout")
      |> add_param(:body, :body, git_checkout_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {400, ExDaytona.Model.ErrorResponse},
      {404, ExDaytona.Model.ErrorResponse},
      {409, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Clone a Git repository
  Clone a Git repository to the specified path. Defaults to strict TLS verification; set insecure_skip_tls=true to skip verification for self-signed or private-CA Git servers.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `git_clone_request` (GitCloneRequest): Clone repository request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec clone_repository(Tesla.Env.client(), ExDaytona.Model.GitCloneRequest.t(), keyword()) ::
          {:ok, nil} | {:ok, ExDaytona.Model.ErrorResponse.t()} | {:error, Tesla.Env.t()}
  def clone_repository(connection, git_clone_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/git/clone")
      |> add_param(:body, :body, git_clone_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {400, ExDaytona.Model.ErrorResponse},
      {401, ExDaytona.Model.ErrorResponse},
      {403, ExDaytona.Model.ErrorResponse},
      {404, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Commit changes
  Commit staged changes to the Git repository

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `git_commit_request` (GitCommitRequest): Commit request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.GitCommitResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec commit_changes(Tesla.Env.client(), ExDaytona.Model.GitCommitRequest.t(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, ExDaytona.Model.GitCommitResponse.t()}
          | {:error, Tesla.Env.t()}
  def commit_changes(connection, git_commit_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/git/commit")
      |> add_param(:body, :body, git_commit_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.GitCommitResponse},
      {400, ExDaytona.Model.ErrorResponse},
      {409, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Configure Git user
  Configure the Git user name and email at the given scope

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `git_configure_user_request` (GitConfigureUserRequest): Configure user request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec configure_user(Tesla.Env.client(), ExDaytona.Model.GitConfigureUserRequest.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def configure_user(connection, git_configure_user_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/git/config/user")
      |> add_param(:body, :body, git_configure_user_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Create a new branch
  Create a new branch in the Git repository

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `git_branch_request` (GitBranchRequest): Create branch request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_branch(Tesla.Env.client(), ExDaytona.Model.GitBranchRequest.t(), keyword()) ::
          {:ok, nil} | {:ok, ExDaytona.Model.ErrorResponse.t()} | {:error, Tesla.Env.t()}
  def create_branch(connection, git_branch_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/git/branches")
      |> add_param(:body, :body, git_branch_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, false},
      {400, ExDaytona.Model.ErrorResponse},
      {409, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Delete a branch
  Delete a branch from the Git repository

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `git_delete_branch_request` (GitDeleteBranchRequest): Delete branch request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_branch(Tesla.Env.client(), ExDaytona.Model.GitDeleteBranchRequest.t(), keyword()) ::
          {:ok, nil} | {:ok, ExDaytona.Model.ErrorResponse.t()} | {:error, Tesla.Env.t()}
  def delete_branch(connection, git_delete_branch_request, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/git/branches")
      |> add_param(:body, :body, git_delete_branch_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {400, ExDaytona.Model.ErrorResponse},
      {404, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Get commit history
  Get the commit history of the Git repository

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `path` (String.t): Repository path
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%GitCommitInfo{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_commit_history(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, [ExDaytona.Model.GitCommitInfo.t()]}
          | {:error, Tesla.Env.t()}
  def get_commit_history(connection, path, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/git/history")
      |> add_param(:query, :path, path)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.GitCommitInfo},
      {404, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Get a Git config value
  Get a Git config value at the given scope (null when unset)

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `key` (String.t): Config key (e.g. user.name)
  - `opts` (keyword): Optional parameters
    - `:path` (String.t): Repository path (required for local scope)
    - `:scope` (String.t): Config scope: global (default), local or system

  ### Returns

  - `{:ok, ExDaytona.Model.GitConfigResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_git_config(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.GitConfigResponse.t()} | {:error, Tesla.Env.t()}
  def get_git_config(connection, key, opts \\ []) do
    optional_params = %{
      :path => :query,
      :scope => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/git/config")
      |> add_param(:query, :key, key)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.GitConfigResponse}
    ])
  end

  @doc """
  Get Git status
  Get the Git status of the repository at the specified path

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `path` (String.t): Repository path
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.GitStatus.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_status(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()} | {:ok, ExDaytona.Model.GitStatus.t()} | {:error, Tesla.Env.t()}
  def get_status(connection, path, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/git/status")
      |> add_param(:query, :path, path)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.GitStatus},
      {400, ExDaytona.Model.ErrorResponse},
      {404, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Initialize a Git repository
  Initialize a new Git repository at the specified path

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `git_init_request` (GitInitRequest): Init repository request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec init_repository(Tesla.Env.client(), ExDaytona.Model.GitInitRequest.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def init_repository(connection, git_init_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/git/init")
      |> add_param(:body, :body, git_init_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, false}
    ])
  end

  @doc """
  List branches
  Get a list of all branches in the Git repository

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `path` (String.t): Repository path
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.ListBranchResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_branches(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, ExDaytona.Model.ListBranchResponse.t()}
          | {:error, Tesla.Env.t()}
  def list_branches(connection, path, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/git/branches")
      |> add_param(:query, :path, path)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ListBranchResponse},
      {404, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  List remotes
  List the remotes configured in the Git repository

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `path` (String.t): Repository path
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.ListRemotesResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_remotes(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.ListRemotesResponse.t()} | {:error, Tesla.Env.t()}
  def list_remotes(connection, path, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/git/remotes")
      |> add_param(:query, :path, path)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ListRemotesResponse}
    ])
  end

  @doc """
  Pull changes from remote
  Pull changes from the remote Git repository

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `git_pull_request` (GitPullRequest): Pull request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec pull_changes(Tesla.Env.client(), ExDaytona.Model.GitPullRequest.t(), keyword()) ::
          {:ok, nil} | {:ok, ExDaytona.Model.ErrorResponse.t()} | {:error, Tesla.Env.t()}
  def pull_changes(connection, git_pull_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/git/pull")
      |> add_param(:body, :body, git_pull_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {400, ExDaytona.Model.ErrorResponse},
      {401, ExDaytona.Model.ErrorResponse},
      {403, ExDaytona.Model.ErrorResponse},
      {404, ExDaytona.Model.ErrorResponse},
      {409, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Push changes to remote
  Push local changes to the remote Git repository

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `git_push_request` (GitPushRequest): Push request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec push_changes(Tesla.Env.client(), ExDaytona.Model.GitPushRequest.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def push_changes(connection, git_push_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/git/push")
      |> add_param(:body, :body, git_push_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Reset repository
  Reset the current HEAD to the specified state

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `git_reset_request` (GitResetRequest): Reset request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec reset_changes(Tesla.Env.client(), ExDaytona.Model.GitResetRequest.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def reset_changes(connection, git_reset_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/git/reset")
      |> add_param(:body, :body, git_reset_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Restore files
  Restore working tree files or unstage changes

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `git_restore_request` (GitRestoreRequest): Restore request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec restore_files(Tesla.Env.client(), ExDaytona.Model.GitRestoreRequest.t(), keyword()) ::
          {:ok, nil} | {:ok, ExDaytona.Model.ErrorResponse.t()} | {:error, Tesla.Env.t()}
  def restore_files(connection, git_restore_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/git/restore")
      |> add_param(:body, :body, git_restore_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {400, ExDaytona.Model.ErrorResponse},
      {401, ExDaytona.Model.ErrorResponse},
      {403, ExDaytona.Model.ErrorResponse},
      {409, ExDaytona.Model.ErrorResponse},
      {500, ExDaytona.Model.ErrorResponse}
    ])
  end

  @doc """
  Set a Git config value
  Set a Git config key/value at the given scope

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `git_set_config_request` (GitSetConfigRequest): Set config request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec set_git_config(Tesla.Env.client(), ExDaytona.Model.GitSetConfigRequest.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def set_git_config(connection, git_set_config_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/git/config")
      |> add_param(:body, :body, git_set_config_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end
end
