# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.Info do
  @moduledoc """
  API calls for all endpoints tagged `Info`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Get user home directory
  Get the current user home directory path.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.UserHomeDirResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_user_home_dir(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.UserHomeDirResponse.t()} | {:error, Tesla.Env.t()}
  def get_user_home_dir(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/user-home-dir")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.UserHomeDirResponse}
    ])
  end

  @doc """
  Get version
  Get the current daemon version

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_version(Tesla.Env.client(), keyword()) ::
          {:ok, %{optional(String.t()) => String.t()}} | {:error, Tesla.Env.t()}
  def get_version(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/version")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}}
    ])
  end

  @doc """
  Get working directory
  Get the current working directory path. This is default directory used for running commands.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.WorkDirResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_work_dir(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.WorkDirResponse.t()} | {:error, Tesla.Env.t()}
  def get_work_dir(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/work-dir")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.WorkDirResponse}
    ])
  end
end
