# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.Port do
  @moduledoc """
  API calls for all endpoints tagged `Port`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Get active ports
  Get a list of all currently active ports

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.PortList.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_ports(Tesla.Env.client(), keyword()) :: {:ok, ExDaytona.Model.PortList.t()} | {:error, Tesla.Env.t()}
  def get_ports(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/port")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.PortList}
    ])
  end

  @doc """
  Check if port is in use
  Check if a specific port is currently in use

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `port` (integer()): Port number (3000-9999)
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.IsPortInUseResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec is_port_in_use(Tesla.Env.client(), integer(), keyword()) ::
          {:ok, ExDaytona.Model.ErrorResponse.t()}
          | {:ok, ExDaytona.Model.IsPortInUseResponse.t()}
          | {:error, Tesla.Env.t()}
  def is_port_in_use(connection, port, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/port/#{port}/in-use")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.IsPortInUseResponse},
      {400, ExDaytona.Model.ErrorResponse}
    ])
  end
end
