# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.Preview do
  @moduledoc """
  API calls for all endpoints tagged `Preview`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Get sandbox ID from signed preview URL token

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `signed_preview_token` (String.t): Signed preview URL token
  - `port` (number()): Port number to get sandbox ID from signed preview URL token
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_sandbox_id_from_signed_preview_url_token(Tesla.Env.client(), String.t(), number(), keyword()) ::
          {:ok, String.t()} | {:error, Tesla.Env.t()}
  def get_sandbox_id_from_signed_preview_url_token(connection, signed_preview_token, port, opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/preview/#{signed_preview_token}/#{port}/sandbox-id")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, false}
      ],
      opts
    )
  end

  @doc """
  Get the signing key for a sandbox

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): ID of the sandbox
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_signing_key(Tesla.Env.client(), String.t(), keyword()) :: {:ok, String.t()} | {:error, Tesla.Env.t()}
  def get_signing_key(connection, sandbox_id, opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/preview/#{sandbox_id}/signing-key")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, false}
      ],
      opts
    )
  end

  @doc """
  Check if user has access to the sandbox

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, boolean()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec has_sandbox_access(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, nil} | {:ok, boolean()} | {:error, Tesla.Env.t()}
  def has_sandbox_access(connection, sandbox_id, opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/preview/#{sandbox_id}/access")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, false},
        {404, false}
      ],
      opts
    )
  end

  @doc """
  Check if the preview warning page is enabled for the sandbox

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): ID of the sandbox, or a signed preview URL token (requires the port query param)
  - `opts` (keyword): Optional parameters
    - `:port` (number()): Port the signed preview URL token was issued for. Required when sandboxId is a signed token.

  ### Returns

  - `{:ok, ExDaytona.Model.PreviewWarning.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec is_preview_warning_enabled(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.PreviewWarning.t()} | {:error, Tesla.Env.t()}
  def is_preview_warning_enabled(connection, sandbox_id, opts \\ []) do
    optional_params = %{
      :port => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/preview/#{sandbox_id}/preview-warning")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, ExDaytona.Model.PreviewWarning}
      ],
      opts
    )
  end

  @doc """
  Check if sandbox is public

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): ID of the sandbox
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, boolean()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec is_sandbox_public(Tesla.Env.client(), String.t(), keyword()) :: {:ok, boolean()} | {:error, Tesla.Env.t()}
  def is_sandbox_public(connection, sandbox_id, opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/preview/#{sandbox_id}/public")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, false}
      ],
      opts
    )
  end

  @doc """
  Check if sandbox auth token is valid

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): ID of the sandbox
  - `auth_token` (String.t): Auth token of the sandbox
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, boolean()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec is_valid_auth_token(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, boolean()} | {:error, Tesla.Env.t()}
  def is_valid_auth_token(connection, sandbox_id, auth_token, opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/preview/#{sandbox_id}/validate/#{auth_token}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, false}
      ],
      opts
    )
  end
end
