# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.Regions do
  @moduledoc """
  API calls for all endpoints tagged `Regions`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  List all shared regions

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%Region{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_shared_regions(Tesla.Env.client(), keyword()) ::
          {:ok, [ExDaytona.Model.Region.t()]} | {:error, Tesla.Env.t()}
  def list_shared_regions(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/shared-regions")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Region}
    ])
  end
end
