# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.Runners do
  @moduledoc """
  API calls for all endpoints tagged `Runners`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Create runner

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `create_runner` (CreateRunner): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.CreateRunnerResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_runner(Tesla.Env.client(), ExDaytona.Model.CreateRunner.t(), keyword()) ::
          {:ok, ExDaytona.Model.CreateRunnerResponse.t()} | {:error, Tesla.Env.t()}
  def create_runner(connection, create_runner, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/runners")
      |> add_param(:body, :body, create_runner)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, ExDaytona.Model.CreateRunnerResponse}
    ])
  end

  @doc """
  Delete runner

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Runner ID
  - `opts` (keyword): Optional parameters
    - `:force` (boolean()): Delete the runner without waiting for sandboxes already marked for destruction. Requires the runner to have stopped reporting as ready.
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_runner(Tesla.Env.client(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def delete_runner(connection, id, opts \\ []) do
    optional_params = %{
      :force => :query,
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:delete)
      |> url("/runners/#{id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false}
    ])
  end

  @doc """
  Get info for authenticated runner

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.RunnerFull.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_info_for_authenticated_runner(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.RunnerFull.t()} | {:error, Tesla.Env.t()}
  def get_info_for_authenticated_runner(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/runners/me")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.RunnerFull}
    ])
  end

  @doc """
  Get runner by ID

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Runner ID
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Runner.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_runner_by_id(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Runner.t()} | {:error, Tesla.Env.t()}
  def get_runner_by_id(connection, id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/runners/#{id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Runner}
    ])
  end

  @doc """
  Get runner by sandbox ID

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.RunnerFull.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_runner_by_sandbox_id(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.RunnerFull.t()} | {:error, Tesla.Env.t()}
  def get_runner_by_sandbox_id(connection, sandbox_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/runners/by-sandbox/#{sandbox_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.RunnerFull}
    ])
  end

  @doc """
  Get runner by ID

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Runner ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.RunnerFull.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_runner_full_by_id(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.RunnerFull.t()} | {:error, Tesla.Env.t()}
  def get_runner_full_by_id(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/runners/#{id}/full")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.RunnerFull}
    ])
  end

  @doc """
  Get runners by snapshot ref

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `ref` (String.t): Snapshot ref
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%RunnerSnapshotDto{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_runners_by_snapshot_ref(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, [ExDaytona.Model.RunnerSnapshotDto.t()]} | {:error, Tesla.Env.t()}
  def get_runners_by_snapshot_ref(connection, ref, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/runners/by-snapshot-ref")
      |> add_param(:query, :ref, ref)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.RunnerSnapshotDto}
    ])
  end

  @doc """
  Get snapshot refs for authenticated runner

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%String.t{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_snapshot_refs_for_authenticated_runner(Tesla.Env.client(), keyword()) ::
          {:ok, [String.t()]} | {:error, Tesla.Env.t()}
  def get_snapshot_refs_for_authenticated_runner(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/runners/me/snapshots")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, []}
    ])
  end

  @doc """
  List all runners

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:regionId` (String.t): Filter runners by region ID
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, [%Runner{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_runners(Tesla.Env.client(), keyword()) :: {:ok, [ExDaytona.Model.Runner.t()]} | {:error, Tesla.Env.t()}
  def list_runners(connection, opts \\ []) do
    optional_params = %{
      :regionId => :query,
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/runners")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Runner}
    ])
  end

  @doc """
  Runner healthcheck
  Endpoint for version 2 runners to send healthcheck and metrics. Updates lastChecked timestamp and runner metrics.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `runner_healthcheck` (RunnerHealthcheck): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec runner_healthcheck(Tesla.Env.client(), ExDaytona.Model.RunnerHealthcheck.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def runner_healthcheck(connection, runner_healthcheck, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/runners/healthcheck")
      |> add_param(:body, :body, runner_healthcheck)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Update runner draining status

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Runner ID
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Runner.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_runner_draining(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Runner.t()} | {:error, Tesla.Env.t()}
  def update_runner_draining(connection, id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:patch)
      |> url("/runners/#{id}/draining")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Runner}
    ])
  end

  @doc """
  Update runner scheduling status

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Runner ID
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Runner.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_runner_scheduling(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Runner.t()} | {:error, Tesla.Env.t()}
  def update_runner_scheduling(connection, id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:patch)
      |> url("/runners/#{id}/scheduling")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Runner}
    ])
  end
end
