# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.Sandbox do
  @moduledoc """
  API calls for all endpoints tagged `Sandbox`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Archive sandbox

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec archive_sandbox(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def archive_sandbox(connection, sandbox_id_or_name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/archive")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Create sandbox backup
  Deprecated: backups are managed automatically. This endpoint is a no-op kept for compatibility.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_backup(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def create_backup(connection, sandbox_id_or_name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/backup")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Create a new sandbox

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `create_sandbox` (CreateSandbox): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_sandbox(Tesla.Env.client(), ExDaytona.Model.CreateSandbox.t(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def create_sandbox(connection, create_sandbox, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox")
      |> add_param(:body, :body, create_sandbox)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Create a snapshot from a sandbox

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): 
  - `create_sandbox_snapshot` (CreateSandboxSnapshot): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_sandbox_snapshot(Tesla.Env.client(), String.t(), ExDaytona.Model.CreateSandboxSnapshot.t(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def create_sandbox_snapshot(connection, sandbox_id_or_name, create_sandbox_snapshot, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/snapshot")
      |> add_param(:body, :body, create_sandbox_snapshot)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Create SSH access for sandbox

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:expiresInMinutes` (number()): Expiration time in minutes (default: 60)

  ### Returns

  - `{:ok, ExDaytona.Model.SshAccessDto.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_ssh_access(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.SshAccessDto.t()} | {:error, Tesla.Env.t()}
  def create_ssh_access(connection, sandbox_id_or_name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :expiresInMinutes => :query
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/ssh-access")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.SshAccessDto}
    ])
  end

  @doc """
  Delete sandbox

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_sandbox(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def delete_sandbox(connection, sandbox_id_or_name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:delete)
      |> url("/sandbox/#{sandbox_id_or_name}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Expire signed preview URL for a sandbox port

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `port` (integer()): Port number to expire signed preview URL for
  - `token` (String.t): Token to expire signed preview URL for
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec expire_signed_port_preview_url(Tesla.Env.client(), String.t(), integer(), String.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def expire_signed_port_preview_url(connection, sandbox_id_or_name, port, token, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/ports/#{port}/signed-preview-url/#{token}/expire")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Fork a sandbox

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): 
  - `fork_sandbox` (ForkSandbox): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec fork_sandbox(Tesla.Env.client(), String.t(), ExDaytona.Model.ForkSandbox.t(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def fork_sandbox(connection, sandbox_id_or_name, fork_sandbox, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/fork")
      |> add_param(:body, :body, fork_sandbox)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Get build logs
  This endpoint is deprecated. Use `getBuildLogsUrl` instead.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:follow` (boolean()): Whether to follow the logs stream

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_build_logs(Tesla.Env.client(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def get_build_logs(connection, sandbox_id_or_name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :follow => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/#{sandbox_id_or_name}/build-logs")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Get build logs URL

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Url.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_build_logs_url(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Url.t()} | {:error, Tesla.Env.t()}
  def get_build_logs_url(connection, sandbox_id_or_name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/#{sandbox_id_or_name}/build-logs-url")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Url}
    ])
  end

  @doc """
  Get organization by sandbox ID

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): ID of the sandbox
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Organization.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_organization_by_sandbox_id(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Organization.t()} | {:error, Tesla.Env.t()}
  def get_organization_by_sandbox_id(connection, sandbox_id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/#{sandbox_id}/organization")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Organization}
    ])
  end

  @doc """
  Get preview URL for a sandbox port

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `port` (number()): Port number to get preview URL for
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.PortPreviewUrl.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_port_preview_url(Tesla.Env.client(), String.t(), number(), keyword()) ::
          {:ok, ExDaytona.Model.PortPreviewUrl.t()} | {:error, Tesla.Env.t()}
  def get_port_preview_url(connection, sandbox_id_or_name, port, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/#{sandbox_id_or_name}/ports/#{port}/preview-url")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.PortPreviewUrl}
    ])
  end

  @doc """
  Get region quota by sandbox ID

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): ID of the sandbox
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.RegionQuota.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_region_quota_by_sandbox_id(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.RegionQuota.t()} | {:error, Tesla.Env.t()}
  def get_region_quota_by_sandbox_id(connection, sandbox_id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/#{sandbox_id}/region-quota")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.RegionQuota}
    ])
  end

  @doc """
  Get sandbox details
  Sandboxes destroyed by spot preemption remain retrievable for 24 hours so `spotEvictedAt` can be read.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:verbose` (boolean()): Include verbose output

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_sandbox(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def get_sandbox(connection, sandbox_id_or_name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :verbose => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/#{sandbox_id_or_name}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Get sandbox fork ancestor chain

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, [%Sandbox{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_sandbox_ancestors(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, [ExDaytona.Model.Sandbox.t()]} | {:error, Tesla.Env.t()}
  def get_sandbox_ancestors(connection, sandbox_id_or_name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/#{sandbox_id_or_name}/ancestors")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Get sandbox fork children

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:includeDestroyed` (boolean()): 

  ### Returns

  - `{:ok, [%Sandbox{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_sandbox_forks(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, [ExDaytona.Model.Sandbox.t()]} | {:error, Tesla.Env.t()}
  def get_sandbox_forks(connection, sandbox_id_or_name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :includeDestroyed => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/#{sandbox_id_or_name}/forks")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Get sandbox logs
  Retrieve OTEL logs for a sandbox within a time range

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): ID of the sandbox
  - `from` (DateTime.t): Start of time range (ISO 8601)
  - `to` (DateTime.t): End of time range (ISO 8601)
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:page` (number()): Page number (1-indexed)
    - `:limit` (number()): Number of items per page
    - `:severities` ([String.t]): Filter by severity levels (DEBUG, INFO, WARN, ERROR)
    - `:search` (String.t): Search in log body

  ### Returns

  - `{:ok, ExDaytona.Model.PaginatedLogs.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_sandbox_logs(Tesla.Env.client(), String.t(), DateTime.t(), DateTime.t(), keyword()) ::
          {:ok, ExDaytona.Model.PaginatedLogs.t()} | {:error, Tesla.Env.t()}
  def get_sandbox_logs(connection, sandbox_id, from, to, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :page => :query,
      :limit => :query,
      :severities => :query,
      :search => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/#{sandbox_id}/telemetry/logs")
      |> add_param(:query, :from, from)
      |> add_param(:query, :to, to)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.PaginatedLogs}
    ])
  end

  @doc """
  Get sandbox metrics
  Retrieve OTEL metrics for a sandbox within a time range

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): ID of the sandbox
  - `from` (DateTime.t): Start of time range (ISO 8601)
  - `to` (DateTime.t): End of time range (ISO 8601)
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:metricNames` ([String.t]): Filter by metric names

  ### Returns

  - `{:ok, ExDaytona.Model.MetricsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_sandbox_metrics(Tesla.Env.client(), String.t(), DateTime.t(), DateTime.t(), keyword()) ::
          {:ok, ExDaytona.Model.MetricsResponse.t()} | {:error, Tesla.Env.t()}
  def get_sandbox_metrics(connection, sandbox_id, from, to, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :metricNames => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/#{sandbox_id}/telemetry/metrics")
      |> add_param(:query, :from, from)
      |> add_param(:query, :to, to)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.MetricsResponse}
    ])
  end

  @doc """
  Get sandbox fork parent

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_sandbox_parent(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def get_sandbox_parent(connection, sandbox_id_or_name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/#{sandbox_id_or_name}/parent")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Get the signing key for a sandbox

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): ID of the sandbox
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_sandbox_signing_key(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, String.t()} | {:error, Tesla.Env.t()}
  def get_sandbox_signing_key(connection, sandbox_id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/#{sandbox_id}/signing-key")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Get trace spans
  Retrieve all spans for a specific trace

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): ID of the sandbox
  - `trace_id` (String.t): ID of the trace
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, [%TraceSpan{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_sandbox_trace_spans(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, [ExDaytona.Model.TraceSpan.t()]} | {:error, Tesla.Env.t()}
  def get_sandbox_trace_spans(connection, sandbox_id, trace_id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/#{sandbox_id}/telemetry/traces/#{trace_id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.TraceSpan}
    ])
  end

  @doc """
  Get sandbox traces
  Retrieve OTEL traces for a sandbox within a time range

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): ID of the sandbox
  - `from` (DateTime.t): Start of time range (ISO 8601)
  - `to` (DateTime.t): End of time range (ISO 8601)
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:page` (number()): Page number (1-indexed)
    - `:limit` (number()): Number of items per page

  ### Returns

  - `{:ok, ExDaytona.Model.PaginatedTraces.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_sandbox_traces(Tesla.Env.client(), String.t(), DateTime.t(), DateTime.t(), keyword()) ::
          {:ok, ExDaytona.Model.PaginatedTraces.t()} | {:error, Tesla.Env.t()}
  def get_sandbox_traces(connection, sandbox_id, from, to, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :page => :query,
      :limit => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/#{sandbox_id}/telemetry/traces")
      |> add_param(:query, :from, from)
      |> add_param(:query, :to, to)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.PaginatedTraces}
    ])
  end

  @doc """
  Get sandboxes for the authenticated runner

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:states` (String.t): Comma-separated list of sandbox states to filter by
    - `:skipReconcilingSandboxes` (boolean()): Skip sandboxes where state differs from desired state

  ### Returns

  - `{:ok, [%Sandbox{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_sandboxes_for_runner(Tesla.Env.client(), keyword()) ::
          {:ok, [ExDaytona.Model.Sandbox.t()]} | {:error, Tesla.Env.t()}
  def get_sandboxes_for_runner(connection, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :states => :query,
      :skipReconcilingSandboxes => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/for-runner")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Get signed preview URL for a sandbox port

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `port` (integer()): Port number to get signed preview URL for
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:expiresInSeconds` (integer()): Expiration time in seconds (default: 60 seconds)

  ### Returns

  - `{:ok, ExDaytona.Model.SignedPortPreviewUrl.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_signed_port_preview_url(Tesla.Env.client(), String.t(), integer(), keyword()) ::
          {:ok, ExDaytona.Model.SignedPortPreviewUrl.t()} | {:error, Tesla.Env.t()}
  def get_signed_port_preview_url(connection, sandbox_id_or_name, port, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :expiresInSeconds => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/#{sandbox_id_or_name}/ports/#{port}/signed-preview-url")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.SignedPortPreviewUrl}
    ])
  end

  @doc """
  Get toolbox proxy URL for a sandbox

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): ID of the sandbox
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.ToolboxProxyUrl.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_toolbox_proxy_url(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.ToolboxProxyUrl.t()} | {:error, Tesla.Env.t()}
  def get_toolbox_proxy_url(connection, sandbox_id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/#{sandbox_id}/toolbox-proxy-url")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ToolboxProxyUrl}
    ])
  end

  @doc """
  List sandboxes
  Advanced filtering and ordering. Eventually consistent.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:cursor` (String.t): Pagination cursor from a previous response
    - `:limit` (number()): Number of results per page
    - `:id` (String.t): Filter by ID prefix (case-insensitive)
    - `:name` (String.t): Filter by name prefix (case-insensitive)
    - `:labels` (String.t): JSON encoded labels to filter by
    - `:includeErroredDeleted` (boolean()): Include results with errored state and deleted desired state
    - `:includeWarm` (boolean()): Include unclaimed warm pool sandboxes (excluded by default)
    - `:states` ([ExDaytona.Model.SandboxState.t]): List of states to filter by.
    - `:snapshots` ([String.t]): List of snapshot names to filter by
    - `:regionIds` ([String.t]): List of regions IDs to filter by
    - `:sandboxClasses` ([ExDaytona.Model.SandboxClass.t]): List of sandbox classes to filter by
    - `:minCpu` (number()): Minimum CPU
    - `:maxCpu` (number()): Maximum CPU
    - `:minMemoryGiB` (number()): Minimum memory in GiB
    - `:maxMemoryGiB` (number()): Maximum memory in GiB
    - `:minDiskGiB` (number()): Minimum disk space in GiB
    - `:maxDiskGiB` (number()): Maximum disk space in GiB
    - `:isPublic` (boolean()): Filter by public status
    - `:isRecoverable` (boolean()): Filter by recoverable status
    - `:createdAtAfter` (DateTime.t): Include items created after this timestamp
    - `:createdAtBefore` (DateTime.t): Include items created before this timestamp
    - `:lastEventAfter` (DateTime.t): Include items with last event after this timestamp
    - `:lastEventBefore` (DateTime.t): Include items with last event before this timestamp
    - `:autoDestroyAtAfter` (DateTime.t): Include items scheduled for auto destroy after this timestamp
    - `:autoDestroyAtBefore` (DateTime.t): Include items scheduled for auto destroy before this timestamp
    - `:sort` (SandboxListSortField): Field to sort by
    - `:order` (SandboxListSortDirection): Direction to sort by

  ### Returns

  - `{:ok, ExDaytona.Model.ListSandboxesResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_sandboxes(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.ListSandboxesResponse.t()} | {:error, Tesla.Env.t()}
  def list_sandboxes(connection, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :cursor => :query,
      :limit => :query,
      :id => :query,
      :name => :query,
      :labels => :query,
      :includeErroredDeleted => :query,
      :includeWarm => :query,
      :states => :query,
      :snapshots => :query,
      :regionIds => :query,
      :sandboxClasses => :query,
      :minCpu => :query,
      :maxCpu => :query,
      :minMemoryGiB => :query,
      :maxMemoryGiB => :query,
      :minDiskGiB => :query,
      :maxDiskGiB => :query,
      :isPublic => :query,
      :isRecoverable => :query,
      :createdAtAfter => :query,
      :createdAtBefore => :query,
      :lastEventAfter => :query,
      :lastEventBefore => :query,
      :autoDestroyAtAfter => :query,
      :autoDestroyAtBefore => :query,
      :sort => :query,
      :order => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ListSandboxesResponse}
    ])
  end

  @doc """
  [DEPRECATED] List all sandboxes paginated

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:page` (number()): Page number of the results
    - `:limit` (number()): Number of results per page
    - `:id` (String.t): Filter by partial ID match
    - `:name` (String.t): Filter by partial name match
    - `:labels` (String.t): JSON encoded labels to filter by
    - `:includeErroredDeleted` (boolean()): Include results with errored state and deleted desired state
    - `:states` ([String.t]): List of states to filter by
    - `:snapshots` ([String.t]): List of snapshot names to filter by
    - `:regions` ([String.t]): List of regions to filter by
    - `:minCpu` (number()): Minimum CPU
    - `:maxCpu` (number()): Maximum CPU
    - `:minMemoryGiB` (number()): Minimum memory in GiB
    - `:maxMemoryGiB` (number()): Maximum memory in GiB
    - `:minDiskGiB` (number()): Minimum disk space in GiB
    - `:maxDiskGiB` (number()): Maximum disk space in GiB
    - `:lastEventAfter` (DateTime.t): Include items with last event after this timestamp
    - `:lastEventBefore` (DateTime.t): Include items with last event before this timestamp
    - `:sort` (String.t): Field to sort by
    - `:order` (String.t): Direction to sort by

  ### Returns

  - `{:ok, ExDaytona.Model.PaginatedSandboxesDeprecated.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_sandboxes_paginated_deprecated(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.PaginatedSandboxesDeprecated.t()} | {:error, Tesla.Env.t()}
  def list_sandboxes_paginated_deprecated(connection, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :page => :query,
      :limit => :query,
      :id => :query,
      :name => :query,
      :labels => :query,
      :includeErroredDeleted => :query,
      :states => :query,
      :snapshots => :query,
      :regions => :query,
      :minCpu => :query,
      :maxCpu => :query,
      :minMemoryGiB => :query,
      :maxMemoryGiB => :query,
      :minDiskGiB => :query,
      :maxDiskGiB => :query,
      :lastEventAfter => :query,
      :lastEventBefore => :query,
      :sort => :query,
      :order => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/paginated")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.PaginatedSandboxesDeprecated}
    ])
  end

  @doc """
  Pause sandbox

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec pause_sandbox(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def pause_sandbox(connection, sandbox_id_or_name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/pause")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Recover sandbox from error state

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:skipStart` (boolean()): If true, the sandbox is left in STOPPED after recovery instead of being started.

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec recover_sandbox(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def recover_sandbox(connection, sandbox_id_or_name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :skipStart => :query
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/recover")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Replace sandbox labels

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `sandbox_labels` (SandboxLabels): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.SandboxLabels.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec replace_labels(Tesla.Env.client(), String.t(), ExDaytona.Model.SandboxLabels.t(), keyword()) ::
          {:ok, ExDaytona.Model.SandboxLabels.t()} | {:error, Tesla.Env.t()}
  def replace_labels(connection, sandbox_id_or_name, sandbox_labels, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:put)
      |> url("/sandbox/#{sandbox_id_or_name}/labels")
      |> add_param(:body, :body, sandbox_labels)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.SandboxLabels}
    ])
  end

  @doc """
  Resize sandbox resources

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `resize_sandbox` (ResizeSandbox): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec resize_sandbox(Tesla.Env.client(), String.t(), ExDaytona.Model.ResizeSandbox.t(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def resize_sandbox(connection, sandbox_id_or_name, resize_sandbox, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/resize")
      |> add_param(:body, :body, resize_sandbox)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Resolve sandbox secrets

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): Sandbox ID
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, [%ResolveSandboxSecrets200ResponseInner{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec resolve_sandbox_secrets(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, [ExDaytona.Model.ResolveSandboxSecrets200ResponseInner.t()]} | {:error, Tesla.Env.t()}
  def resolve_sandbox_secrets(connection, sandbox_id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/#{sandbox_id}/secrets")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ResolveSandboxSecrets200ResponseInner}
    ])
  end

  @doc """
  Revoke SSH access for sandbox

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:token` (String.t): SSH access token to revoke. If not provided, all SSH access for the sandbox will be revoked.

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec revoke_ssh_access(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def revoke_ssh_access(connection, sandbox_id_or_name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :token => :query
    }

    request =
      %{}
      |> method(:delete)
      |> url("/sandbox/#{sandbox_id_or_name}/ssh-access")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Rotate the signing key, invalidating all previously signed URLs

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): ID of the sandbox
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec rotate_signing_key(Tesla.Env.client(), String.t(), keyword()) :: {:ok, String.t()} | {:error, Tesla.Env.t()}
  def rotate_signing_key(connection, sandbox_id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id}/signing-key/rotate")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Set sandbox auto-archive interval

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `interval` (number()): Auto-archive interval in minutes (0 means the maximum interval will be used)
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec set_auto_archive_interval(Tesla.Env.client(), String.t(), number(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def set_auto_archive_interval(connection, sandbox_id_or_name, interval, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/autoarchive/#{interval}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Set sandbox auto-delete interval

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `interval` (number()): Auto-delete interval in minutes (negative value means disabled, 0 means delete immediately upon stopping)
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec set_auto_delete_interval(Tesla.Env.client(), String.t(), number(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def set_auto_delete_interval(connection, sandbox_id_or_name, interval, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/autodelete/#{interval}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Set sandbox auto-pause interval

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `interval` (number()): Auto-pause interval in minutes (0 to disable)
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec set_auto_pause_interval(Tesla.Env.client(), String.t(), number(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def set_auto_pause_interval(connection, sandbox_id_or_name, interval, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/autopause/#{interval}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Set sandbox auto-stop interval

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `interval` (number()): Auto-stop interval in minutes (0 to disable)
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec set_autostop_interval(Tesla.Env.client(), String.t(), number(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def set_autostop_interval(connection, sandbox_id_or_name, interval, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/autostop/#{interval}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Set sandbox TTL

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `ttl_minutes` (number()): Maximum time to live in minutes, re-anchored from the current time (0 to disable). When it elapses the sandbox is destroyed, even if it is stopped, paused, or archived
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec set_ttl(Tesla.Env.client(), String.t(), number(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def set_ttl(connection, sandbox_id_or_name, ttl_minutes, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/ttl/#{ttl_minutes}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Start or resume sandbox
  Starts a stopped or archived sandbox, or resumes a paused sandbox. The transition taken depends on the current sandbox state.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec start_sandbox(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def start_sandbox(connection, sandbox_id_or_name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/start")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Stop sandbox

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:force` (boolean()): Force stop the sandbox using SIGKILL instead of SIGTERM

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec stop_sandbox(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def stop_sandbox(connection, sandbox_id_or_name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :force => :query
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/stop")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Update sandbox last activity

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): ID of the sandbox
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:body` (UpdateLastActivity): 

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_last_activity(Tesla.Env.client(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def update_last_activity(connection, sandbox_id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id}/last-activity")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, false}
    ])
  end

  @doc """
  Update sandbox network settings
  Changes outbound network policy on the runner for a running sandbox (for example block all traffic, restore access, or set a CIDR allow list).

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `update_sandbox_network_settings` (UpdateSandboxNetworkSettings): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_network_settings(
          Tesla.Env.client(),
          String.t(),
          ExDaytona.Model.UpdateSandboxNetworkSettings.t(),
          keyword()
        ) :: {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def update_network_settings(connection, sandbox_id_or_name, update_sandbox_network_settings, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/network-settings")
      |> add_param(:body, :body, update_sandbox_network_settings)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Update public status

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `is_public` (boolean()): Public status to set
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_public_status(Tesla.Env.client(), String.t(), boolean(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def update_public_status(connection, sandbox_id_or_name, is_public, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/sandbox/#{sandbox_id_or_name}/public/#{is_public}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Update sandbox secrets
  Replaces the set of vault secrets mounted in the sandbox. Attached, detached and rotated secrets take effect for outbound requests within seconds. New env vars become visible to processes spawned after the update; a sandbox created without any secrets must be restarted for newly attached secrets to work.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id_or_name` (String.t): ID or name of the sandbox
  - `update_sandbox_secrets` (UpdateSandboxSecrets): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Sandbox.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_sandbox_secrets(Tesla.Env.client(), String.t(), ExDaytona.Model.UpdateSandboxSecrets.t(), keyword()) ::
          {:ok, ExDaytona.Model.Sandbox.t()} | {:error, Tesla.Env.t()}
  def update_sandbox_secrets(connection, sandbox_id_or_name, update_sandbox_secrets, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:put)
      |> url("/sandbox/#{sandbox_id_or_name}/secrets")
      |> add_param(:body, :body, update_sandbox_secrets)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Sandbox}
    ])
  end

  @doc """
  Update sandbox state

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `sandbox_id` (String.t): ID of the sandbox
  - `update_sandbox_state_dto` (UpdateSandboxStateDto): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_sandbox_state(Tesla.Env.client(), String.t(), ExDaytona.Model.UpdateSandboxStateDto.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def update_sandbox_state(connection, sandbox_id, update_sandbox_state_dto, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:put)
      |> url("/sandbox/#{sandbox_id}/state")
      |> add_param(:body, :body, update_sandbox_state_dto)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Validate SSH access for sandbox

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `token` (String.t): SSH access token to validate
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.SshAccessValidationDto.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec validate_ssh_access(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.SshAccessValidationDto.t()} | {:error, Tesla.Env.t()}
  def validate_ssh_access(connection, token, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/sandbox/ssh-access/validate")
      |> add_param(:query, :token, token)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.SshAccessValidationDto}
    ])
  end
end
