# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.Secret do
  @moduledoc """
  API calls for all endpoints tagged `Secret`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Create secret

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `create_secret` (CreateSecret): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Secret.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_secret(Tesla.Env.client(), ExDaytona.Model.CreateSecret.t(), keyword()) ::
          {:ok, ExDaytona.Model.Secret.t()} | {:error, Tesla.Env.t()}
  def create_secret(connection, create_secret, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/secret")
      |> add_param(:body, :body, create_secret)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {201, ExDaytona.Model.Secret}
      ],
      opts
    )
  end

  @doc """
  Delete secret

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `secret_id` (String.t): ID of the secret
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_secret(Tesla.Env.client(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def delete_secret(connection, secret_id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:delete)
      |> url("/secret/#{secret_id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {204, false}
      ],
      opts
    )
  end

  @doc """
  Get secret

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `secret_id` (String.t): ID of the secret
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Secret.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_secret(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Secret.t()} | {:error, Tesla.Env.t()}
  def get_secret(connection, secret_id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/secret/#{secret_id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, ExDaytona.Model.Secret}
      ],
      opts
    )
  end

  @doc """
  List secrets
  This endpoint is deprecated and fails for organizations with more than 1500 secrets. Use `listSecretsPaginated` instead.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, [%Secret{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_secrets(Tesla.Env.client(), keyword()) :: {:ok, [ExDaytona.Model.Secret.t()]} | {:error, Tesla.Env.t()}
  def list_secrets(connection, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/secret")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, ExDaytona.Model.Secret}
      ],
      opts
    )
  end

  @doc """
  List secrets with pagination

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:cursor` (String.t): Pagination cursor from a previous response
    - `:limit` (number()): Number of results per page
    - `:name` (String.t): Filter by partial name match
    - `:sort` (String.t): Field to sort by
    - `:order` (String.t): Direction to sort by

  ### Returns

  - `{:ok, ExDaytona.Model.ListSecretsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_secrets_paginated(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.ListSecretsResponse.t()} | {:error, Tesla.Env.t()}
  def list_secrets_paginated(connection, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :cursor => :query,
      :limit => :query,
      :name => :query,
      :sort => :query,
      :order => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/secret/paginated")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, ExDaytona.Model.ListSecretsResponse}
      ],
      opts
    )
  end

  @doc """
  Update secret

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `secret_id` (String.t): ID of the secret
  - `update_secret` (UpdateSecret): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Secret.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_secret(Tesla.Env.client(), String.t(), ExDaytona.Model.UpdateSecret.t(), keyword()) ::
          {:ok, ExDaytona.Model.Secret.t()} | {:error, Tesla.Env.t()}
  def update_secret(connection, secret_id, update_secret, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:patch)
      |> url("/secret/#{secret_id}")
      |> add_param(:body, :body, update_secret)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, ExDaytona.Model.Secret}
      ],
      opts
    )
  end
end
