# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.Server do
  @moduledoc """
  API calls for all endpoints tagged `Server`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Initialize toolbox server
  Set the auth token and initialize telemetry for the toolbox server

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `initialize_request` (InitializeRequest): Initialization request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec initialize(Tesla.Env.client(), ExDaytona.Model.InitializeRequest.t(), keyword()) ::
          {:ok, %{optional(String.t()) => String.t()}} | {:error, Tesla.Env.t()}
  def initialize(connection, initialize_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/init")
      |> add_param(:body, :body, initialize_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}}
    ])
  end

  @doc """
  Update process environment
  Update the daemon's process environment. Newly spawned processes, sessions and PTYs inherit the change; already-running processes keep their environment.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `update_env_request` (UpdateEnvRequest): Environment update request
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_env(Tesla.Env.client(), ExDaytona.Model.UpdateEnvRequest.t(), keyword()) ::
          {:ok, %{optional(String.t()) => String.t()}} | {:error, Tesla.Env.t()}
  def update_env(connection, update_env_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/env")
      |> add_param(:body, :body, update_env_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}}
    ])
  end
end
