# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.Snapshots do
  @moduledoc """
  API calls for all endpoints tagged `Snapshots`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Activate a snapshot

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Snapshot ID
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.SnapshotDto.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec activate_snapshot(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, nil} | {:ok, ExDaytona.Model.SnapshotDto.t()} | {:error, Tesla.Env.t()}
  def activate_snapshot(connection, id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/snapshots/#{id}/activate")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.SnapshotDto},
      {400, false},
      {404, false}
    ])
  end

  @doc """
  Create a new snapshot

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `create_snapshot` (CreateSnapshot): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.SnapshotDto.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_snapshot(Tesla.Env.client(), ExDaytona.Model.CreateSnapshot.t(), keyword()) ::
          {:ok, nil} | {:ok, ExDaytona.Model.SnapshotDto.t()} | {:error, Tesla.Env.t()}
  def create_snapshot(connection, create_snapshot, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/snapshots")
      |> add_param(:body, :body, create_snapshot)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.SnapshotDto},
      {400, false}
    ])
  end

  @doc """
  Deactivate a snapshot

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Snapshot ID
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec deactivate_snapshot(Tesla.Env.client(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def deactivate_snapshot(connection, id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/snapshots/#{id}/deactivate")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false}
    ])
  end

  @doc """
  List all snapshots

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:page` (number()): Page number of the results
    - `:limit` (number()): Number of results per page
    - `:name` (String.t): Filter by partial name match
    - `:sourceSandboxId` (String.t): Filter by the ID of the sandbox the snapshot was created from
    - `:sort` (String.t): Field to sort by
    - `:order` (String.t): Direction to sort by

  ### Returns

  - `{:ok, ExDaytona.Model.PaginatedSnapshots.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_all_snapshots(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.PaginatedSnapshots.t()} | {:error, Tesla.Env.t()}
  def get_all_snapshots(connection, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :page => :query,
      :limit => :query,
      :name => :query,
      :sourceSandboxId => :query,
      :sort => :query,
      :order => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/snapshots")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.PaginatedSnapshots}
    ])
  end

  @doc """
  Get snapshot by ID or name

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Snapshot ID or name
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.SnapshotDto.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_snapshot(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, nil} | {:ok, ExDaytona.Model.SnapshotDto.t()} | {:error, Tesla.Env.t()}
  def get_snapshot(connection, id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/snapshots/#{id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.SnapshotDto},
      {404, false}
    ])
  end

  @doc """
  Get snapshot build logs
  This endpoint is deprecated. Use `getSnapshotBuildLogsUrl` instead.

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Snapshot ID
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:follow` (boolean()): Whether to follow the logs stream

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_snapshot_build_logs(Tesla.Env.client(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def get_snapshot_build_logs(connection, id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :follow => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/snapshots/#{id}/build-logs")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end

  @doc """
  Get snapshot build logs URL

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Snapshot ID
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.Url.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_snapshot_build_logs_url(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.Url.t()} | {:error, Tesla.Env.t()}
  def get_snapshot_build_logs_url(connection, id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/snapshots/#{id}/build-logs-url")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.Url}
    ])
  end

  @doc """
  Delete snapshot

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Snapshot ID
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec remove_snapshot(Tesla.Env.client(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def remove_snapshot(connection, id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:delete)
      |> url("/snapshots/#{id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false}
    ])
  end
end
