# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.Telemetry do
  @moduledoc """
  API calls for all endpoints tagged `Telemetry`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Get sandbox logs
  Returns paginated log entries with optional severity and search filters

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): Organization ID
  - `sandbox_id` (String.t): Sandbox ID
  - `from` (String.t): Start time (RFC3339)
  - `to` (String.t): End time (RFC3339)
  - `opts` (keyword): Optional parameters
    - `:severity` (String.t): Comma-separated severity levels
    - `:search` (String.t): Search text (ILIKE)
    - `:limit` (integer()): Page size
    - `:offset` (integer()): Offset

  ### Returns

  - `{:ok, [%ModelsLogEntry{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec organization_organization_id_sandbox_sandbox_id_telemetry_logs_get(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          String.t(),
          String.t(),
          keyword()
        ) :: {:ok, [ExDaytona.Model.ModelsLogEntry.t()]} | {:error, Tesla.Env.t()}
  def organization_organization_id_sandbox_sandbox_id_telemetry_logs_get(
        connection,
        organization_id,
        sandbox_id,
        from,
        to,
        opts \\ []
      ) do
    optional_params = %{
      :severity => :query,
      :search => :query,
      :limit => :query,
      :offset => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/organization/#{organization_id}/sandbox/#{sandbox_id}/telemetry/logs")
      |> add_param(:query, :from, from)
      |> add_param(:query, :to, to)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ModelsLogEntry}
    ])
  end

  @doc """
  Get sandbox metrics
  Returns gauge metrics aggregated in 1-minute intervals

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): Organization ID
  - `sandbox_id` (String.t): Sandbox ID
  - `from` (String.t): Start time (RFC3339)
  - `to` (String.t): End time (RFC3339)
  - `opts` (keyword): Optional parameters
    - `:metricNames` (String.t): Comma-separated metric names

  ### Returns

  - `{:ok, [%ModelsMetricPoint{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec organization_organization_id_sandbox_sandbox_id_telemetry_metrics_get(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          String.t(),
          String.t(),
          keyword()
        ) :: {:ok, [ExDaytona.Model.ModelsMetricPoint.t()]} | {:error, Tesla.Env.t()}
  def organization_organization_id_sandbox_sandbox_id_telemetry_metrics_get(
        connection,
        organization_id,
        sandbox_id,
        from,
        to,
        opts \\ []
      ) do
    optional_params = %{
      :metricNames => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/organization/#{organization_id}/sandbox/#{sandbox_id}/telemetry/metrics")
      |> add_param(:query, :from, from)
      |> add_param(:query, :to, to)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ModelsMetricPoint}
    ])
  end

  @doc """
  Get sandbox traces
  Returns paginated trace summaries with span counts and root span info

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): Organization ID
  - `sandbox_id` (String.t): Sandbox ID
  - `from` (String.t): Start time (RFC3339)
  - `to` (String.t): End time (RFC3339)
  - `opts` (keyword): Optional parameters
    - `:limit` (integer()): Page size
    - `:offset` (integer()): Offset

  ### Returns

  - `{:ok, [%ModelsTraceSummary{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec organization_organization_id_sandbox_sandbox_id_telemetry_traces_get(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          String.t(),
          String.t(),
          keyword()
        ) :: {:ok, [ExDaytona.Model.ModelsTraceSummary.t()]} | {:error, Tesla.Env.t()}
  def organization_organization_id_sandbox_sandbox_id_telemetry_traces_get(
        connection,
        organization_id,
        sandbox_id,
        from,
        to,
        opts \\ []
      ) do
    optional_params = %{
      :limit => :query,
      :offset => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/organization/#{organization_id}/sandbox/#{sandbox_id}/telemetry/traces")
      |> add_param(:query, :from, from)
      |> add_param(:query, :to, to)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ModelsTraceSummary}
    ])
  end

  @doc """
  Get trace spans
  Returns all spans belonging to a specific trace ID

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): Organization ID
  - `sandbox_id` (String.t): Sandbox ID
  - `trace_id` (String.t): Trace ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%ModelsSpan{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec organization_organization_id_sandbox_sandbox_id_telemetry_traces_trace_id_get(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          String.t(),
          keyword()
        ) :: {:ok, [ExDaytona.Model.ModelsSpan.t()]} | {:error, Tesla.Env.t()}
  def organization_organization_id_sandbox_sandbox_id_telemetry_traces_trace_id_get(
        connection,
        organization_id,
        sandbox_id,
        trace_id,
        _opts \\ []
      ) do
    request =
      %{}
      |> method(:get)
      |> url("/organization/#{organization_id}/sandbox/#{sandbox_id}/telemetry/traces/#{trace_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ModelsSpan}
    ])
  end
end
