# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.Usage do
  @moduledoc """
  API calls for all endpoints tagged `Usage`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Get sandbox usage periods
  Returns individual usage records for a specific sandbox within a time range

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): Organization ID
  - `sandbox_id` (String.t): Sandbox ID
  - `from` (String.t): Start time (RFC3339)
  - `to` (String.t): End time (RFC3339)
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%ModelsUsagePeriod{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec organization_organization_id_sandbox_sandbox_id_usage_get(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          String.t(),
          String.t(),
          keyword()
        ) :: {:ok, [ExDaytona.Model.ModelsUsagePeriod.t()]} | {:error, Tesla.Env.t()}
  def organization_organization_id_sandbox_sandbox_id_usage_get(
        connection,
        organization_id,
        sandbox_id,
        from,
        to,
        _opts \\ []
      ) do
    request =
      %{}
      |> method(:get)
      |> url("/organization/#{organization_id}/sandbox/#{sandbox_id}/usage")
      |> add_param(:query, :from, from)
      |> add_param(:query, :to, to)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ModelsUsagePeriod}
    ])
  end

  @doc """
  Get aggregated usage
  Returns organization-level resource usage totals for a given time period

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): Organization ID
  - `from` (String.t): Start time (RFC3339)
  - `to` (String.t): End time (RFC3339)
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.ModelsAggregatedUsage.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec organization_organization_id_usage_aggregated_get(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          String.t(),
          keyword()
        ) :: {:ok, ExDaytona.Model.ModelsAggregatedUsage.t()} | {:error, Tesla.Env.t()}
  def organization_organization_id_usage_aggregated_get(connection, organization_id, from, to, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/organization/#{organization_id}/usage/aggregated")
      |> add_param(:query, :from, from)
      |> add_param(:query, :to, to)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ModelsAggregatedUsage}
    ])
  end

  @doc """
  Get usage chart data
  Returns resource usage data points for a given time period with auto-scaled resolution

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): Organization ID
  - `from` (String.t): Start time (RFC3339)
  - `to` (String.t): End time (RFC3339)
  - `opts` (keyword): Optional parameters
    - `:region` (String.t): Region filter

  ### Returns

  - `{:ok, [%ModelsUsageChartPoint{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec organization_organization_id_usage_chart_get(Tesla.Env.client(), String.t(), String.t(), String.t(), keyword()) ::
          {:ok, [ExDaytona.Model.ModelsUsageChartPoint.t()]} | {:error, Tesla.Env.t()}
  def organization_organization_id_usage_chart_get(connection, organization_id, from, to, opts \\ []) do
    optional_params = %{
      :region => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/organization/#{organization_id}/usage/chart")
      |> add_param(:query, :from, from)
      |> add_param(:query, :to, to)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ModelsUsageChartPoint}
    ])
  end

  @doc """
  Get per-sandbox usage
  Returns resource usage aggregated per sandbox for a given time period

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): Organization ID
  - `from` (String.t): Start time (RFC3339)
  - `to` (String.t): End time (RFC3339)
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%ModelsSandboxUsage{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec organization_organization_id_usage_sandbox_get(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          String.t(),
          keyword()
        ) :: {:ok, [ExDaytona.Model.ModelsSandboxUsage.t()]} | {:error, Tesla.Env.t()}
  def organization_organization_id_usage_sandbox_get(connection, organization_id, from, to, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/organization/#{organization_id}/usage/sandbox")
      |> add_param(:query, :from, from)
      |> add_param(:query, :to, to)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.ModelsSandboxUsage}
    ])
  end
end
