# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.Users do
  @moduledoc """
  API calls for all endpoints tagged `Users`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Confirm (link) a pending SSO account link

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec confirm_pending_sso_link(Tesla.Env.client(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def confirm_pending_sso_link(connection, id, opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/users/me/pending-sso-links/#{id}/confirm")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {204, false}
      ],
      opts
    )
  end

  @doc """
  Dismiss a pending SSO account link

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec dismiss_pending_sso_link(Tesla.Env.client(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def dismiss_pending_sso_link(connection, id, opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/users/me/pending-sso-links/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {204, false}
      ],
      opts
    )
  end

  @doc """
  Enroll in SMS MFA

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec enroll_in_sms_mfa(Tesla.Env.client(), keyword()) :: {:ok, String.t()} | {:error, Tesla.Env.t()}
  def enroll_in_sms_mfa(connection, opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/users/mfa/sms/enroll")
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, false}
      ],
      opts
    )
  end

  @doc """
  Get authenticated user

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, ExDaytona.Model.User.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_authenticated_user(Tesla.Env.client(), keyword()) ::
          {:ok, ExDaytona.Model.User.t()} | {:error, Tesla.Env.t()}
  def get_authenticated_user(connection, opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/users/me")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, ExDaytona.Model.User}
      ],
      opts
    )
  end

  @doc """
  Get available account providers

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%AccountProvider{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_available_account_providers(Tesla.Env.client(), keyword()) ::
          {:ok, [ExDaytona.Model.AccountProvider.t()]} | {:error, Tesla.Env.t()}
  def get_available_account_providers(connection, opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/users/account-providers")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, ExDaytona.Model.AccountProvider}
      ],
      opts
    )
  end

  @doc """
  Link account

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `create_linked_account` (CreateLinkedAccount): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec link_account(Tesla.Env.client(), ExDaytona.Model.CreateLinkedAccount.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def link_account(connection, create_linked_account, opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/users/linked-accounts")
      |> add_param(:body, :body, create_linked_account)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {204, false}
      ],
      opts
    )
  end

  @doc """
  List pending SSO account links for the authenticated user

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%PendingSsoLink{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_pending_sso_links(Tesla.Env.client(), keyword()) ::
          {:ok, [ExDaytona.Model.PendingSsoLink.t()]} | {:error, Tesla.Env.t()}
  def list_pending_sso_links(connection, opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/users/me/pending-sso-links")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, ExDaytona.Model.PendingSsoLink}
      ],
      opts
    )
  end

  @doc """
  Unlink account

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `provider` (String.t): 
  - `provider_user_id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec unlink_account(Tesla.Env.client(), String.t(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def unlink_account(connection, provider, provider_user_id, opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/users/linked-accounts/#{provider}/#{provider_user_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {204, false}
      ],
      opts
    )
  end
end
