# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.Volumes do
  @moduledoc """
  API calls for all endpoints tagged `Volumes`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Create a new volume

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `create_volume` (CreateVolume): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.VolumeDto.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_volume(Tesla.Env.client(), ExDaytona.Model.CreateVolume.t(), keyword()) ::
          {:ok, ExDaytona.Model.VolumeDto.t()} | {:error, Tesla.Env.t()}
  def create_volume(connection, create_volume, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/volumes")
      |> add_param(:body, :body, create_volume)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, ExDaytona.Model.VolumeDto}
      ],
      opts
    )
  end

  @doc """
  Delete volume

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `volume_id` (String.t): ID of the volume
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_volume(Tesla.Env.client(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def delete_volume(connection, volume_id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:delete)
      |> url("/volumes/#{volume_id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, false},
        {409, false}
      ],
      opts
    )
  end

  @doc """
  Get volume details

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `volume_id` (String.t): ID of the volume
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.VolumeDto.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_volume(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.VolumeDto.t()} | {:error, Tesla.Env.t()}
  def get_volume(connection, volume_id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/volumes/#{volume_id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, ExDaytona.Model.VolumeDto}
      ],
      opts
    )
  end

  @doc """
  Get volume details by name

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `name` (String.t): Name of the volume
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.VolumeDto.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_volume_by_name(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.VolumeDto.t()} | {:error, Tesla.Env.t()}
  def get_volume_by_name(connection, name, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/volumes/by-name/#{name}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, ExDaytona.Model.VolumeDto}
      ],
      opts
    )
  end

  @doc """
  List all volumes

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID
    - `:includeDeleted` (boolean()): Include deleted volumes in the response

  ### Returns

  - `{:ok, [%VolumeDto{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_volumes(Tesla.Env.client(), keyword()) :: {:ok, [ExDaytona.Model.VolumeDto.t()]} | {:error, Tesla.Env.t()}
  def list_volumes(connection, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers,
      :includeDeleted => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/volumes")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response(
      [
        {200, ExDaytona.Model.VolumeDto}
      ],
      opts
    )
  end
end
