# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.WarmPools do
  @moduledoc """
  API calls for all endpoints tagged `WarmPools`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Create a warm pool

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `create_warm_pool` (CreateWarmPool): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.WarmPool.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_warm_pool(Tesla.Env.client(), ExDaytona.Model.CreateWarmPool.t(), keyword()) ::
          {:ok, ExDaytona.Model.WarmPool.t()} | {:error, Tesla.Env.t()}
  def create_warm_pool(connection, create_warm_pool, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/warm-pools")
      |> add_param(:body, :body, create_warm_pool)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, ExDaytona.Model.WarmPool}
    ])
  end

  @doc """
  Delete a warm pool

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Warm pool ID
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_warm_pool(Tesla.Env.client(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def delete_warm_pool(connection, id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:delete)
      |> url("/warm-pools/#{id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false}
    ])
  end

  @doc """
  List warm pools for the organization

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, [%WarmPool{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_warm_pools(Tesla.Env.client(), keyword()) ::
          {:ok, [ExDaytona.Model.WarmPool.t()]} | {:error, Tesla.Env.t()}
  def list_warm_pools(connection, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/warm-pools")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.WarmPool}
    ])
  end

  @doc """
  Update a warm pool size

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `id` (String.t): Warm pool ID
  - `update_warm_pool` (UpdateWarmPool): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.WarmPool.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_warm_pool(Tesla.Env.client(), String.t(), ExDaytona.Model.UpdateWarmPool.t(), keyword()) ::
          {:ok, ExDaytona.Model.WarmPool.t()} | {:error, Tesla.Env.t()}
  def update_warm_pool(connection, id, update_warm_pool, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:patch)
      |> url("/warm-pools/#{id}")
      |> add_param(:body, :body, update_warm_pool)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.WarmPool}
    ])
  end
end
