# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech)
# using the Elixir SDK Generator template (https://github.com/houllette/elixir-sdk-generator).
# Do not edit this file manually — edit the templates and regenerate instead.

defmodule ExDaytona.Api.Webhooks do
  @moduledoc """
  API calls for all endpoints tagged `Webhooks`.
  """

  alias ExDaytona.Connection
  import ExDaytona.RequestBuilder

  @doc """
  Get Svix Consumer App Portal access for an organization

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.WebhookAppPortalAccess.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_app_portal_access(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.WebhookAppPortalAccess.t()} | {:error, Tesla.Env.t()}
  def get_app_portal_access(connection, organization_id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/webhooks/organizations/#{organization_id}/app-portal-access")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.WebhookAppPortalAccess}
    ])
  end

  @doc """
  Get webhook initialization status for an organization

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.WebhookInitializationStatus.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_initialization_status(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, nil} | {:ok, ExDaytona.Model.WebhookInitializationStatus.t()} | {:error, Tesla.Env.t()}
  def get_initialization_status(connection, organization_id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/webhooks/organizations/#{organization_id}/initialization-status")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, ExDaytona.Model.WebhookInitializationStatus},
      {404, false}
    ])
  end

  @doc """
  Initialize webhooks for an organization

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): Organization ID
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, ExDaytona.Model.WebhookInitializationStatus.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec initialize_webhooks(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, ExDaytona.Model.WebhookInitializationStatus.t()} | {:error, Tesla.Env.t()}
  def initialize_webhooks(connection, organization_id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/webhooks/organizations/#{organization_id}/initialize")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, ExDaytona.Model.WebhookInitializationStatus}
    ])
  end

  @doc """
  Refresh cached endpoint presence flag for an organization

  ### Parameters

  - `connection` (ExDaytona.Connection): Connection to server
  - `organization_id` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:"X-Daytona-Organization-ID"` (String.t): Use with JWT to specify the organization ID

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec refresh_endpoints(Tesla.Env.client(), String.t(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def refresh_endpoints(connection, organization_id, opts \\ []) do
    optional_params = %{
      :"X-Daytona-Organization-ID" => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/webhooks/organizations/#{organization_id}/refresh-endpoints")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, false}
    ])
  end
end
