#!/usr/bin/env bash
set -euo pipefail

# Fetch and merge the Daytona OpenAPI specs into a single spec file.
#
# Daytona does not publish one combined spec. Its API surface is split across
# three documents (see SPEC_* below): the main platform API (OpenAPI 3.0) and
# the toolbox/analytics APIs (Swagger 2.0). This script downloads all three,
# converts the Swagger 2.0 documents to OpenAPI 3.0 (via swagger2openapi),
# and merges them into one spec so a single generated SDK covers everything.
#
# The merge is safe because the three specs share no path, operationId, tag,
# or schema names — this script verifies that on every run and fails loudly
# if upstream ever introduces a collision.
#
# Note on base URLs: only the main platform API lives at the merged spec's
# server URL (https://app.daytona.io/api). Toolbox endpoints are served per
# sandbox at {toolboxProxyUrl}/{sandboxId}, and analytics at
# https://analytics.app.daytona.io — callers select the right base URL via
# Connection.new(base_url: ...). See the README.
#
# Usage: fetch-spec.sh [OUTPUT_PATH]   (default: openapi-spec.yaml)
#
# Local spec fixes still belong in spec-patches/ (applied below and by
# scripts/regenerate.sh) — never hand-edit the merged output, this script
# overwrites it.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
OUTPUT="${1:-$PROJECT_ROOT/openapi-spec.yaml}"

SPEC_MAIN_URL="https://www.daytona.io/docs/openapi.json"
SPEC_TOOLBOX_URL="https://www.daytona.io/docs/toolbox-openapi.json"
SPEC_ANALYTICS_URL="https://www.daytona.io/docs/analytics-openapi.json"

# Production base URL for the main platform API (the merged spec's server).
MAIN_BASE_URL="https://app.daytona.io/api"

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

echo_info() { echo -e "${GREEN}[FETCH-SPEC]${NC} $*"; }
echo_error() { echo -e "${RED}[FETCH-SPEC]${NC} $*"; }

for cmd in curl jq; do
  if ! command -v "$cmd" &> /dev/null; then
    echo_error "$cmd is required"
    exit 1
  fi
done

# swagger2openapi converts the Swagger 2.0 documents to OpenAPI 3.0
if command -v swagger2openapi &> /dev/null; then
  CONVERT_CMD="swagger2openapi"
elif command -v npx &> /dev/null; then
  CONVERT_CMD="npx --yes swagger2openapi"
else
  echo_error "swagger2openapi not found (install node/npx or 'npm install -g swagger2openapi')"
  exit 1
fi

WORK_DIR=$(mktemp -d)
trap 'rm -rf "$WORK_DIR"' EXIT

echo_info "Downloading specs..."
curl -fsSL "$SPEC_MAIN_URL" -o "$WORK_DIR/main.json"
curl -fsSL "$SPEC_TOOLBOX_URL" -o "$WORK_DIR/toolbox.swagger.json"
curl -fsSL "$SPEC_ANALYTICS_URL" -o "$WORK_DIR/analytics.swagger.json"

echo_info "Converting Swagger 2.0 specs to OpenAPI 3.0..."
$CONVERT_CMD --patch "$WORK_DIR/toolbox.swagger.json" -o "$WORK_DIR/toolbox.json" > /dev/null
$CONVERT_CMD --patch "$WORK_DIR/analytics.swagger.json" -o "$WORK_DIR/analytics.json" > /dev/null

# Guard: the merge blindly unions paths/schemas/operationIds/tags, which is
# only correct while the three specs share none. Fail loudly if that changes.
check_no_collisions() {
  local what="$1" filter="$2"
  local a b c
  a=$(jq -r "$filter" "$WORK_DIR/main.json" | sort -u)
  b=$(jq -r "$filter" "$WORK_DIR/toolbox.json" | sort -u)
  c=$(jq -r "$filter" "$WORK_DIR/analytics.json" | sort -u)
  local dupes
  dupes=$(printf '%s\n%s\n%s\n' "$a" "$b" "$c" | sort | uniq -d)
  if [[ -n "$dupes" ]]; then
    echo_error "Upstream specs now share $what — the blind merge is no longer safe:"
    echo "$dupes"
    echo_error "Resolve the collision (e.g. rename via a pre-merge step here) before regenerating."
    exit 1
  fi
}

echo_info "Checking for cross-spec collisions..."
check_no_collisions "paths" '.paths | keys[]'
check_no_collisions "schema names" '.components.schemas // {} | keys[]'
check_no_collisions "operationIds" '[.paths[][] | objects | .operationId // empty] | .[]'
check_no_collisions "tags" '[.paths[][] | objects | .tags // [] | .[]] | unique | .[]'

echo_info "Merging specs..."
jq -S \
  --slurpfile toolbox "$WORK_DIR/toolbox.json" \
  --slurpfile analytics "$WORK_DIR/analytics.json" \
  --arg base_url "$MAIN_BASE_URL" \
  --arg main_url "$SPEC_MAIN_URL" \
  --arg toolbox_url "$SPEC_TOOLBOX_URL" \
  --arg analytics_url "$SPEC_ANALYTICS_URL" \
  '
  .servers = [{url: $base_url}]
  | .info.description =
      "Merged Daytona API spec (generated by scripts/fetch-spec.sh — do not edit by hand).\n"
      + "Sources:\n"
      + "- main platform API: " + $main_url + "\n"
      + "- toolbox API: " + $toolbox_url
      + " (per-sandbox base URL: {toolboxProxyUrl}/{sandboxId})\n"
      + "- analytics API: " + $analytics_url
      + " (base URL: https://analytics.app.daytona.io)"
  | .paths += $toolbox[0].paths + $analytics[0].paths
  | .components.schemas += ($toolbox[0].components.schemas // {}) + ($analytics[0].components.schemas // {})
  | .components.requestBodies = ($toolbox[0].components.requestBodies // {}) + ($analytics[0].components.requestBodies // {})
  | .components.securitySchemes += ($toolbox[0].components.securitySchemes // {}) + ($analytics[0].components.securitySchemes // {})
  ' \
  "$WORK_DIR/main.json" > "$WORK_DIR/merged.json"

# JSON is valid YAML, and jq -S output is deterministic (sorted keys), so
# repeated runs against unchanged upstream specs are byte-identical — which
# the spec-sync workflow relies on for its drift comparison.
mv "$WORK_DIR/merged.json" "$OUTPUT"
echo_info "Wrote merged spec to $OUTPUT"

# Apply local spec patches (see spec-patches/README.md)
if [[ -x "$SCRIPT_DIR/apply-spec-patches.sh" ]]; then
  "$SCRIPT_DIR/apply-spec-patches.sh" "$OUTPUT"
fi

echo_info "Done: $(jq -r '.paths | length' "$OUTPUT") paths, $(jq -r '.components.schemas | length' "$OUTPUT") schemas."
